[Avatar] Update colors
Shopify/polaris-react-archive pull request #11261
Opened 2023-11-30 00:19 UTC by lgriffee

### WHY are these changes introduced?

Part of https://github.com/Shopify/polaris-internal/issues/1077

### WHAT is this pull request doing?

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [ ] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2023-11-30 18:05 UTC, lgriffee commented
/snapit

2023-11-30 18:28 UTC, tjonx approved these changes

2023-11-30 19:51 UTC, annaborg requested changes
• Good on the color changes overall. Colors showing up correctly in the login screen, store switcher, search, org switcher, settings headers, orgs Stores page, orgs Users page. 

• Cannot test if showing up correctly in admin search. If there is above a certain number of Stores in the switcher within an Org admin in Plus, you are able to search for more stores that expand past the amount allowed in that switcher. 

• Not showing up on non-Plus Users and Permissions page
<img width="493" alt="Screenshot 2023-11-30 at 12 41 42 PM" src="https://github.com/Shopify/polaris/assets/79230887/46157fcd-8fc7-4326-8320-463890a9cf64">
<img width="442" alt="Screenshot 2023-11-30 at 12 42 55 PM" src="https://github.com/Shopify/polaris/assets/79230887/c31a067d-cb00-43eb-a64a-fcb0ae3d25cf">


• All Plus users and permissions pages use the same color 
<img width="211" alt="Screenshot 2023-11-30 at 12 47 12 PM" src="https://github.com/Shopify/polaris/assets/79230887/00295d8c-915a-4e37-a050-d15e16a59466">
<img width="248" alt="Screenshot 2023-11-30 at 12 47 26 PM" src="https://github.com/Shopify/polaris/assets/79230887/cae0caa9-03ff-4254-a234-7098d69e856c">
<img width="260" alt="Screenshot 2023-11-30 at 12 47 43 PM" src="https://github.com/Shopify/polaris/assets/79230887/a6b44239-52c1-46a1-8d78-f5145ce86206">

• Did we update the original avatars in account.shopify.com? It looks like they're using the new avatars in the login screen, but reverts back to old when you go to the different URL. I know account isn't react the last time I looked, so is that something we need to worry about right now? 
<img width="303" alt="Screenshot 2023-11-30 at 12 34 32 PM" src="https://github.com/Shopify/polaris/assets/79230887/6310f2a2-40ca-44b9-bda7-eeb0d776d148">

• No longer able to hover over avatars in the Store Settings header for neither Plus or Non-Plus to launch modal to edit and upload custom avatar. 

• Want to make sure that the above functionality persists, in addition to making sure that this PR doesn't cancel out an existing custom avatars that currently exist for Store navigation.

2023-12-01 00:11 UTC, lgriffee commented
@annaborg 

> Good on the color changes overall. Colors showing up correctly in the login screen, store switcher, search, org switcher, settings headers, orgs Stores page, orgs Users page. 

Awesome! 🎉❤️✨ 

> Cannot test if showing up correctly in admin search. If there is above a certain number of Stores in the switcher within an Org admin in Plus, you are able to search for more stores that expand past the amount allowed in that switcher.

I've added more stores to the first business so you can test this now. From what I can tell it seems they are all displaying correctly!

> Not showing up on non-Plus Users and Permissions page 

You know I came across the same issue with Timeline recently (so this issue is currently one in production not something to do with this PR). And I couldn’t figure out why for the longest time but I finally tracked down what’s going on! There’s logic in the Avatar (from [this PR](https://github.com/Shopify/polaris/pull/7038)) that only applies the color styles when there is no source prop defined. So if there is a source provided but it fails to load (say an empty string gets passed in) then it just falls back to grey/initials. I've updated the logic so that if the image fails to load then it defaults back to the colored background instead. I've cut a new snapshot and confirmed the fix works. While loading the avatars are grey but as soon as they get initials they become colored. 

> All Plus users and permissions pages use the same color 

I investigated this and it looks like these are all the same since a blank string is being passed into the Avatar initials prop. I think the best solution for these instances is to add a name prop to that Avatar instance in the admin versus any changes in this PR. I will create a separate PR in the admin for this update.

> Did we update the original avatars in account.shopify.com? It looks like they're using the new avatars in the login screen, but reverts back to old when you go to the different URL. I know account isn't react the last time I looked, so is that something we need to worry about right now? 

Yeah since this is part of identity which is currently on the old rails version of Polaris we won't get updates for free here. That would need to be updated by that team.

> No longer able to hover over avatars in the Store Settings header for neither Plus or Non-Plus to launch modal to edit and upload custom avatar. Want to make sure that the above functionality persists, in addition to making sure that this PR doesn't cancel out an existing custom avatars that currently exist for Store navigation.

I spun up a fresh instance (without any of the changes here and with the latest admin changes) and couldn't get this functionality to work so I think this may be a spin limitation. This PR shouldn't effect that functionality.

2023-12-01 21:57 UTC, lgriffee commented
/snapit

2023-12-05 15:56 UTC, chloerice approved these changes

2023-12-05 15:56 UTC, chloerice commented on .changeset/modern-plums-wonder.md
> +Updated avatar background and text colors
```suggestion
Updated `Avatar` background and text colors
```

2023-12-05 18:49 UTC, merged