Add missing color tokens for Shopify Mobile
Shopify/polaris-react-archive pull request #11345
Opened 2023-12-14 22:06 UTC by sam-b-rose

### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-internal/issues/1309

Shopify Mobile needs additional colors for mobile-specific component styles.

### WHAT is this pull request doing?

Adds the following colors tokens to `@shopify/polaris-tokens`:

- `color-text-critical-secondary`
- `color-text-warning-secondary`
- `color-text-caution-secondary`
- `color-text-success-secondary`
- `color-text-info-secondary`
- `color-scrolling-header-border`

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [ ] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2023-12-14 22:53 UTC, sarahill commented
@dGoligorsky Did you happen to look at the values for these? Looks like they're still using `-11` here. Are you ok with bumping to `-12` for contrast?

2023-12-15 10:53 UTC, dGoligorsky commented
> @dGoligorsky Did you happen to look at the values for these? Looks like they're still using `-11` here. Are you ok with bumping to `-12` for contrast?

Yes, I'm ok with bumping to `-12` for those values (cc @sam-b-rose) . I have that updated in a UI Kit branch I'm working on that also has all the v12 color updates 😃

2023-12-15 16:42 UTC, aaronccasanova approved these changes
🚀

2023-12-18 09:50 UTC, dGoligorsky requested changes
Cool to remove that `color-scrolling-header-border` token 👍

2023-12-18 09:50 UTC, dGoligorsky commented on polaris-tokens/src/themes/base/color.ts
> +  'color-scrolling-header-border': {
From our Slack thread— you've helped identify a zombie token here. `color-scrolling-header-border` is no longer needed and we can leverage a shadow token in its place. Ok to remove this one. 🙏

2023-12-18 16:28 UTC, sarahill approved these changes

2023-12-18 16:31 UTC, sam-b-rose commented on polaris-tokens/src/themes/base/color.ts
> +  'color-scrolling-header-border': {
Sounds good, removed 💥

2023-12-19 12:20 UTC, dGoligorsky approved these changes
Yahoo!

2023-12-19 16:54 UTC, merged