Seperate components into internal-only category
Shopify/polaris-react-archive pull request #11382
Opened 2024-01-02 03:03 UTC by alex-page

### WHY are these changes introduced?

Application Developers trying to build applications with the current Polaris documentation are building poor experiences as they are using components that should not be used for application development. `Navigation` `Frame` `Toast`... will render incorrectly in apps and Application Developers need to use App Bridge API's to correctly build their user interface.

### WHAT is this pull request doing?

This PR hopes to resolve this by moving the components to a new category called `Internal only`.

- All components in our current categories can be used by application developers without issue
- Friction is added to components like `<Modal>` `<Toast>` and `<Loading>` to ensure that Application Developers are not incorrectly using these components
- Shopify employees can still access these components despite them being in a new _more confusing_ location
- Educate users without creating private documentation or shipping breaking changes
- Alerts developers that these components can be removed in a future major version if we decide to move them to a private space

2024-01-02 03:13 UTC, alex-page commented
/stageit

2024-01-02 22:27 UTC, alex-page commented
/stageit

2024-01-03 01:35 UTC, jesstelford commented on polaris.shopify.com/content/components/deprecated/frame.mdx
> +category: Deprecated
Why are these marked as `Deprecated`? Shouldn't it be `Internal`?

Technically the components aren't deprecated, they're still being consumed and have stable APIs, we just want to limit who consumes them to a single external dependant.

2024-01-11 00:37 UTC, alex-page commented on polaris.shopify.com/content/components/deprecated/top-bar.mdx
> +    description: Use to provide structure for the top of an application. Style the top bar component using the app provider component with a theme. Providing just the `background` key for the top bar
```suggestion
    description: Provide structure for the top of an application. Style the top bar component using the app provider component with a theme. Providing just the `background` key for the top bar component theme will result in intelligent defaults being set for complementary colors with contrasting text.
```

2024-01-12 02:06 UTC, alex-page commented on polaris.shopify.com/content/components/deprecated/frame.mdx
> +category: Deprecated
I have two files now for each component. One is deprecated which is visible to 3P developers. The other is in internal only. This felt like the best solution to give internal developers the documentation they need while forcefully redirecting application developers to use app bridge.

2024-01-12 17:03 UTC, craigbrunner approved these changes

2024-01-12 19:27 UTC, themarkappleby commented on polaris.shopify.com/content/components/internal-only/frame.mdx
>  - [Loading](https://polaris.shopify.com/components/loading)
These should all point to the `/internal-only/` equivalents I believe.

2024-01-12 19:28 UTC, themarkappleby commented on polaris.shopify.com/content/components/internal-only/contextual-save-bar.mdx
> +- Save all changes on the page. Avoid scenarios where multiple forms on a single page can be edited at the same time. If specific sections of a page need to be independently editable, use an Edit but
This modal path should be `/internal-only/modal`.

2024-01-12 20:07 UTC, themarkappleby requested changes
This is amazing, thanks so much @alex-page! Just a few minor questions/comments from me 👍

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/content/components/internal-only/frame.mdx
> +The frame component, while not visible in the user interface itself, provides the structure for an application. It wraps the main elements and houses the primary [navigation](https://polaris.shopify.
These should all point to the `/interanl-only/` paths I believe.

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/content/components/internal-only/frame.mdx
>  - [Loading](https://polaris.shopify.com/components/loading)
These should all point to `/internal-only/`.

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/content/components/internal-only/frame.mdx
> +- To display the primary navigation within the frame of an application, use the [navigation](https://polaris.shopify.com/components/deprecated/navigation) component.
`/internal-only/`

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/content/components/internal-only/frame.mdx
> +- To provide quick, at-a-glance feedback on the outcome of an action, use the [toast](https://polaris.shopify.com/components/deprecated/toast) component.
`/internal-only/`

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/content/components/internal-only/loading.mdx
> +
Can this safely be removed? AFAIK it doesn't output due to `frontmatter.status` being falsey here.

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/content/components/internal-only/modal.mdx
> +
Can this safely be removed? AFAIK it doesn't output due to `frontmatter.status` being falsey here.

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/content/components/internal-only/navigation.mdx
> +</StatusBanner>
Can this safely be removed? AFAIK it doesn't output due to `frontmatter.status` being falsey here.

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/content/components/internal-only/toast.mdx
> +</StatusBanner>
Can this safely be removed? AFAIK it doesn't output due to `frontmatter.status` being falsey here.

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/content/components/internal-only/top-bar.mdx
> +</StatusBanner>
Can this safely be removed? AFAIK it doesn't output due to `frontmatter.status` being falsey here.

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/content/components/internal-only/top-bar.mdx
> +  - Use the [navigation component](https://polaris.shopify.com/components/deprecated/navigation) instead
Path should be `/internal-only/`

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/content/components/internal-only/top-bar.mdx
> +- To display the primary navigation within the frame of an application, use the [navigation](https://polaris.shopify.com/components/deprecated/navigation) component.
`/internal-only/`

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/content/components/internal-only/top-bar.mdx
> +- To provide quick, at-a-glance feedback on the outcome of an action, use the [toast](https://polaris.shopify.com/components/deprecated/toast) component.
`/internal-only/`

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/content/components/navigation/fullscreen-bar.mdx
> +- To provide quick, at-a-glance feedback on the outcome of an action, use the [toast](https://polaris.shopify.com/components/deprecated/toast) component.
Can we change this to `use the [App Bridge toast API](https://shopify.dev/docs/api/app-bridge-library/reference/toast).`

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/content/content/voice-and-tone.mdx
> +If this is a task people do regularly, make it clear that the step is complete in a simple and non-intrusive way, like a [toast](/components/deprecated/toast). Consider ways to confirm completion wit
Can we change this to something like:

> If this is a task people do regularly, make it clear that the step is complete in a simple and non-intrusive way, like via the [App Bridge toast](https://shopify.dev/docs/api/app-bridge-library/reference/toast). Consider ways to confirm completion without words or messaging.

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/content/design/interaction-states.mdx
> +**For non-disruptive feedback** on the outcome of an action, use the [toast](https://polaris.shopify.com/components/deprecated/toast) component.
...use the [App Bridge toast API](https://shopify.dev/docs/api/app-bridge-library/reference/toast).

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/src/components/Frame/Frame.module.scss
> +        padding-top: 1rem;
This is causing some unintended spacing in other parts of the navigation.

![Screenshot 2024-01-12 at 2 57 17 PM](https://github.com/Shopify/polaris/assets/1360097/c53d8641-c297-4a69-a38c-02bac34c0b4e)

2024-01-12 20:07 UTC, themarkappleby commented on polaris.shopify.com/src/components/StatusBanner/StatusBanner.tsx
> +          {status === 'Internal' ? ' only' : null}
Is this necessary? I can't find any instances of `frontmatter.status` being set to `Internal`. 

<img width="460" alt="12-05-w47u5-w2tqa" src="https://github.com/Shopify/polaris/assets/1360097/ec194c75-c917-4dc3-a9b8-6b89a7d0d740">

2024-01-14 21:09 UTC, alex-page commented on polaris.shopify.com/content/components/internal-only/frame.mdx
> +The frame component, while not visible in the user interface itself, provides the structure for an application. It wraps the main elements and houses the primary [navigation](https://polaris.shopify.
Ahhhh yes. Any of the internal only paths that reference other internal only components I will update. Public paths I will keep pointing to deprecated. Thanks @themarkappleby.

2024-01-14 22:10 UTC, merged