Added icons package to eslint-ts config and fixed some eslint errors
Shopify/polaris-react-archive pull request #11501
Opened 2024-01-24 19:56 UTC by yurm04

### WHY are these changes introduced?

We noticed that the `polaris-icons` package did not have a tsconfig and was not getting linted as expected. Updated configs and fixed up some of the linting errors that were missed.

### WHAT is this pull request doing?

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [ ] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2024-01-24 20:03 UTC, sam-b-rose requested changes
Looks good! Though, I would remove the `nameRegex` and `expectedFillColors` instead of commenting.

2024-01-24 20:13 UTC, aaronccasanova approved these changes

2024-01-24 20:13 UTC, aaronccasanova commented on .changeset/honest-pens-invent.md
We may want to remove this and add the `Skip Changelog` label

2024-01-24 20:48 UTC, alex-page approved these changes
Legend. Thanks Yurms!

2024-01-28 06:11 UTC, sam-b-rose approved these changes

2024-01-28 21:10 UTC, merged