[ResourceItem] Add `disabled` prop
Shopify/polaris-react-archive pull request #11585
Opened 2024-02-09 21:24 UTC by tauthomas01

### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-internal/issues/1360

The goal of this PR is to add a new `disabled` prop in the `ResourceItem` component. We want to have a disabled state in this component because one of our page is displaying it as a list of items and when we click on a `ResourceItem`, it's loading the same template along with the same list of `ResourceItem`. In that case, if we have a disabled state on the current item, it would be great to prevent users from clicking on it again because it would load the same page.

### WHAT is this pull request doing?

When `disabled` prop is `true` in the `ResourceItem`:
- We hide the `UnstyledLink`/button as well as its accessibility attributes as it's no longer an interactive element. This should read as a regular text.
- The `onClick` should not be triggered when we hit `onKeyUp` or `click` on the disabled element
- The `cursor` style is now `default` + font color follows the `disabled` state [like IndexTable.Row](https://github.com/Shopify/polaris/blob/78ed5fe0d616db8c2cf76f59f9528211f81c23b3/polaris-react/src/components/IndexTable/IndexTable.module.scss#L695)
- The hover state is removed
- `onClick` or `url` prop won't be triggered as long as `disabled: true`
- The checkbox `selectable` state is true

Here is a Playground code snippet below to test. In the example, I've added checkboxes in the `ResourceList` to make sure it still works as expected.

<details>

<summary>Code snippet for playground</summary>

```js
import React, {useState} from 'react';
import type {ResourceListProps} from '@shopify/polaris';

import {
  Page,
  LegacyCard,
  ResourceList,
  ResourceItem,
  Text,
  Avatar,
} from '../src';

export function Playground() {
  const [selectedItems, setSelectedItems] = useState<
    ResourceListProps['selectedItems']
  >([]);

  return (
    <Page title="Playground">
      <LegacyCard>
        <ResourceList
          resourceName={{singular: 'customer', plural: 'customers'}}
          selectable
          selectedItems={selectedItems}
          onSelectionChange={setSelectedItems}
          items={[
            {
              id: '145',
              url: '#',
              avatarSource:
                'https://burst.shopifycdn.com/photos/freelance-designer-working-on-laptop.jpg?width=746',
              name: 'Yi So-Yeon',
              location: 'Gwangju, South Korea',
            },
            {
              id: '146',
              url: '#',
              avatarSource:
                'https://burst.shopifycdn.com/photos/woman-standing-in-front-of-yellow-background.jpg?width=746',
              name: 'Jane Smith',
              location: 'Manhattan, New York',
            },
            {
              id: '147',
              url: '#',
              avatarSource:
                'https://burst.shopifycdn.com/photos/relaxing-in-headphones.jpg?width=746',
              name: 'Grace Baker',
              location: 'Los Angeles, California',
            },
          ]}
          renderItem={(item) => {
            const {id, url, avatarSource, name, location} = item;

            return (
              <ResourceItem
                disabled={id === '145'}
                id={id}
                url={url}
                media={
                  <Avatar
                    customer
                    size="md"
                    name={name}
                    source={avatarSource}
                  />
                }
                accessibilityLabel={`View details for ${name}`}
                name={name}
                onClick={() => console.log('clicked')}
              >
                <h3>
                  <Text fontWeight="bold" as="span">
                    {name}
                  </Text>
                </h3>
                <div>{location}</div>
              </ResourceItem>
            );
          }}
        />
      </LegacyCard>
    </Page>
  );
}
```
</details>

https://github.com/Shopify/polaris/assets/658169/72207888-a7dd-48f8-acf7-2c1f11068d1d

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [x] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2024-02-13 19:27 UTC, chloerice requested changes
Hey @tauthomas01 👋🏽 The active state for ResourceItem is its selected state. The interaction here is a `disabled` state, so let's also make sure to disable the [checkbox](https://github.com/Shopify/polaris/blob/6b93b862da9d6e1f5c118f98a3c45dede33396ec/polaris-react/src/components/ResourceItem/ResourceItem.tsx#L189) when `selectable` is `true`.

2024-02-13 19:27 UTC, chloerice commented on polaris-react/src/components/ResourceItem/ResourceItem.module.scss
> +.active {
```suggestion
.disabled {
```

2024-02-13 19:27 UTC, chloerice commented on polaris-react/src/components/ResourceItem/ResourceItem.tsx
> +  active?: boolean;
```suggestion
  /** Whether or not interaction is disabled */
  disabled?: boolean;
```

2024-02-13 19:27 UTC, chloerice commented on polaris-react/src/components/ResourceItem/ResourceItem.tsx
> +      active,
```suggestion
      disabled,
```

2024-02-13 19:27 UTC, chloerice commented on polaris-react/src/components/ResourceItem/ResourceItem.tsx
> +      active && styles.active,
```suggestion
      disabled && styles.disabled,
```

2024-02-13 19:27 UTC, chloerice commented on polaris-react/src/components/ResourceItem/ResourceItem.tsx
> +            onClick={active ? () => {} : this.handleClick}
```suggestion
            onClick={disabled ? () => {} : this.handleClick}
```

2024-02-13 19:27 UTC, chloerice commented on polaris-react/src/components/ResourceItem/ResourceItem.tsx
> +            {active ? null : accessibleMarkup}
```suggestion
            {disabled ? null : accessibleMarkup}
```

2024-02-13 20:23 UTC, tauthomas01 commented
Hi @chloerice , thank you for the review! I made the changes based on your comments and updated the PR description to reflect the new prop name.

2024-02-13 21:10 UTC, chloerice approved these changes
Thank you for contributing @tauthomas01! 🎉 Can you add the Playground code you wrote as a story for this state?

2024-02-13 21:10 UTC, chloerice commented on .changeset/proud-items-do.md
> +Add a new active prop in ResourceItem component
```suggestion
Added a `disabled` prop to `ResourceItem`
```

2024-02-14 13:49 UTC, tauthomas01 commented
/snapit

2024-02-14 15:10 UTC, merged