1368 icon updates
Shopify/polaris-react-archive pull request #11609
Opened 2024-02-15 20:38 UTC by sam-b-rose

### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-internal/issues/1368

### WHAT is this pull request doing?

Updates icon set for improved consistency.

See Stroybook Playground to review icons updates.

<details>
<summary>Changed icons</summary>
<img width="65" alt="Screenshot 2024-02-16 at 9 37 08 AM" src="https://github.com/Shopify/polaris/assets/11774595/da720266-0895-4887-8116-c55ffec95184">
</details>

2024-02-15 21:04 UTC, aaronccasanova commented on polaris-icons/icons/ChartStackedIcon.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 21"><path fill-rule="evenodd" d="M5.75 6.338c-1.519 0-2.75 1.232-2.75 2.75v3c0 1.52 1.231 2.75 2.75 2.75h8.5c1.519 0 2.75-1.23 2.75-2.75v-3c0-1
Are the `viewBox="0 0 20 21"` changes expected?

2024-02-15 21:11 UTC, lgriffee approved these changes
LGTM! Only question is what @aaronccasanova brought up!

2024-02-15 21:35 UTC, aaronccasanova commented on polaris-icons/icons/ChartStackedIcon.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 21"><path fill-rule="evenodd" d="M5.75 6.338c-1.519 0-2.75 1.232-2.75 2.75v3c0 1.52 1.231 2.75 2.75 2.75h8.5c1.519 0 2.75-1.23 2.75-2.75v-3c0-1
Oh great, we have a [test case](https://github.com/Shopify/polaris/blob/9b0011972bca44065fab4f9b77aed816f47323bf/polaris-icons/tests/validate-svg-content.test.js#L42-L44) for this!

2024-02-15 22:01 UTC, bernardojoaogarcia commented
For some Icons I'm seeing some width changes. Is that an issue with the svg?

Deleted
W: **150px** | H: 150px

 Added
W: **143px** | H: 150px

2024-02-16 05:58 UTC, sam-b-rose commented
@aaronccasanova @bernardojoaogarcia 

> For some Icons I'm seeing some width changes. Is that an issue with the svg?

Yes, I think the issue is the viewbox on some of the SVGs are 20x21, which is causing them to not render at the GitHub preview size of a square 150x150.

@bernardojoaogarcia can you try re-exporting the icons that are 20x21 to the viewbox size of 20x20?

2024-02-20 19:50 UTC, aaronccasanova commented on polaris-icons/tests/validate-svg-content.test.js
> +        const allowedAttributes = ['clipRule', 'd', 'fillRule', 'fillOpacity'];
cc @alex-page Not sure what heuristics you used to determine `allowedAttributes` but I added `clipRule` to resolve 22 test failures. Please provide any insights or alternative suggestions 🙏

2024-02-20 19:55 UTC, bernardojoaogarcia approved these changes
Amazing 🚀 🚢

2024-02-20 20:10 UTC, alex-page commented on polaris-icons/tests/validate-svg-content.test.js
> +        const allowedAttributes = ['clipRule', 'd', 'fillRule', 'fillOpacity'];
What happens if you delete the `clip-rule` from the `path`? From memory they were unnecessary most of the time.

2024-02-20 20:27 UTC, alex-page requested changes
Please delete all the duplicate `clip-rule="evenodd"` and undo the changes to the test. This is good to go after that happens.

2024-02-20 21:21 UTC, alex-page approved these changes

2024-02-20 21:28 UTC, merged