[BulkActions] Bring everything up to the top
Shopify/polaris-react-archive pull request #11622
Opened 2024-02-19 17:26 UTC by mrcthms

### WHY are these changes introduced?

Fixes https://github.com/Shopify/web/issues/119088

We want to further update the bulk/select actions to re-combine them into the same piece of UI. We had broken bulk and select actions up as part of the initial Index Filtering and Search work, but now realise that keeping them colocated is the best UX for our merchants.

### WHAT is this pull request doing?

<img width="1624" alt="Screenshot 2024-02-22 at 12 23 50" src="https://github.com/Shopify/polaris/assets/2562596/11b33a11-474a-42fb-8475-1137da228481">

This PR:

- re-introduces all the select logic to the BulkActions component
- left-align select actions, right-align bulk actions
- rewrites the BulkActions component to a function component from a class component
- updates the logic to show/hide promoted actions, as the previous method was broken
- deprecate the SelectAllActions component
- updates IndexTable & ResourceList to remove SelectAllActions, update BulkActions implementation
- removes the useIsSelectAllActionsSticky hook (never exported, only used to position the SelectAllActions internally within ResourceList/IndexTable

The biggest piece of work is updating how the bulk actions show/rollup logic works. Beforehand, it would either show all promoted actions if they fit, or roll every single one up behind a meatball menu. This wasn't great, as we should show as many as possible in the available space. As part of the update to a function component, we now utilise a similar layout sizing mechanism as we use in both the Tabs and ActionMenu -> Actions components, to render as many promoted actions as we possibly can in the available space.

### How to 🎩

Spin URL for IndexTable: https://admin.web.bulk-ui-refresh.marc-thomas.eu.spin.dev/store/shop1/products?selectedView=all
Spin URL for ResourceList: https://admin.web.bulk-ui-refresh.marc-thomas.eu.spin.dev/store/shop1/products/32
Spin URL for Updated Draft orders (using Shopify/web `ResourceListWithHeader`): https://admin.web.bulk-ui-refresh.marc-thomas.eu.spin.dev/store/shop1/draft_orders?selectedView=all

### 🎩 checklist

- [x] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2024-02-21 12:03 UTC, mrcthms commented
/snapit

2024-02-21 15:15 UTC, mrcthms commented
/snapit

2024-02-21 15:43 UTC, mrcthms commented
/snapit

2024-02-21 16:21 UTC, mrcthms commented
/snapit

2024-02-21 16:55 UTC, mrcthms commented
/snapit

2024-02-22 10:42 UTC, mrcthms commented
/snapit

2024-02-22 16:47 UTC, ouellettejordan requested changes
For items that roll-up into the overflow, a couple changes needed...

- [ ] keep all "promoted actions" in the same section — no divider line between promoted action, however mainting divider line between actions that already existed in the overflow and the promoted actions that roll-up into the overflow

- [ ]  maintain order of items that get rolled up into overflow — ie: original order of items in header area `Bulk edit` / `Set as draft` / `Set as active` — this should translate to this in the overflow menu...

- `Bulk edit`
- `Set as draft`
- `Set as active`

- [x] Draft order bulk select position is broken as well as label is lost (`Actions` as there are none promoted). Let's ensure this isn't happening elsewhere as well.

2024-02-22 16:52 UTC, boyutf commented
Hi @mrcthms , I just tried on your latest snapshot. After commenting out `bulkActions` I can no longer get the `select all in this product` option, it's still tied to `bulkActions` and I wonder what is missing.
This is [where](https://github.com/Shopify/web/blob/main/app/sections/OrganizationSettings/OrganizationTestDrive/OrganizationTable/OrganizationTable.tsx#L203) we are calling the settingsTable which is a wrapper around indexTable

2024-02-22 16:55 UTC, mrcthms commented
@boyutf I haven't made a snapshot with the changes to work without actions/promotedActions, I'll run the command now to create a new snapshot which should include those changes

2024-02-22 16:55 UTC, mrcthms commented
/snapit

2024-02-22 17:26 UTC, mrcthms commented
@ouellettejordan 

> keep all "promoted actions" in the same section — no divider line between promoted action, however mainting divider line between actions that already existed in the overflow and the promoted actions that roll-up into the overflow

This would be a new change compared to how it currently works in the admin, we currently add each promoted action in their own section.

<img width="1624" alt="Screenshot 2024-02-22 at 17 23 23" src="https://github.com/Shopify/polaris/assets/2562596/1f8487e0-0584-4496-b0c4-2e63c5c234b5">

One thing to note about this, is that for promoted actions that contain child actions inside a dropdown, we render the child actions in the meatball menu. Added a little video of how that looks now when they're all rolled up into the same section rather than the promoted actions with child actions having their own section


https://github.com/Shopify/polaris/assets/2562596/a5052aed-7f68-45d5-94c9-07f4c0a61b2d



---

> maintain order of items that get rolled up into overflow — ie: original order of items in header area Bulk edit / Set as draft / Set as active — this should translate to this in the overflow menu...

Would we not want to show as many promoted actions as possible in the space, even if they're not in the same order? In the example video below, we could easily fit the "Export" button next to "Rename customers" when "Edit customers" gets rolled up. Feels like we're wasting available space in a key piece of screen real estate by forcing them to always roll up in the same order

https://github.com/Shopify/polaris/assets/2562596/89436797-fe0c-4fed-9b20-3c67ab670c1e

---

> Draft order bulk select position is broken as well as label is lost (Actions as there are none promoted). Let's ensure this isn't happening elsewhere as well.

That's expected at this stage, the Draft orders index doesn't use the IndexTable so we'd have to make some changes within Shopify/web to support this new BulkActions experience – we'd make sure obviously that we had these updates ready to go for when the Polaris version containing this change is released

2024-02-22 18:07 UTC, mrcthms commented
/snapit

2024-02-23 17:29 UTC, laurkim approved these changes
Looks good from code standpoint 💯 
I have some concerns about the updates to the micro Button styles but most likely just need a bit more clarification on it.

2024-02-23 17:29 UTC, laurkim commented on polaris-react/src/components/BulkActions/BulkActions.tsx
> +    // setState,
🔥

2024-02-23 17:29 UTC, laurkim commented on polaris-react/src/components/BulkActions/BulkActions.tsx
> +    <div className={bulkActionsClassNames} style={width ? {width} : undefined}>
```suggestion
    <div className={styles.BulkActions} style={width ? {width} : undefined}>
```

Light suggestion to just use `styles.BulkActions` directly here and remove `bulkActionsClassNames` variable higher up since classnames aren't being combined.

2024-02-23 17:29 UTC, laurkim commented on polaris-react/src/components/Button/Button.module.scss
> +  }
From what I can tell, the BulkActionButton is rendering a Button without setting a variant (so it's using the default `secondary` variant). I might be missing another case where a monochromePlain is being rendered with bulk actions but if not, is this still needed?

2024-02-23 17:29 UTC, laurkim commented on polaris-react/src/components/IndexTable/IndexTable.tsx
> +    <div className={paginationWrapperClassNames}>
```suggestion
    <div className={styles.PaginationWrapper}>
```

Light suggestion to use class name directly since multiple class names aren't being combined. Would require removing the `paginationWrapperClassNames` variable.

2024-02-23 17:29 UTC, laurkim commented on polaris-react/src/components/IndexTable/IndexTable.tsx
> +        <div className={tableWrapperClassNames}>
```suggestion
        <div className={styles.IndexTableWrapper}>
```

Light suggestion to use class name directly since multiple class names aren't being combined. Would require removing the `tableWrapperClassNames` variable.

2024-02-23 17:29 UTC, laurkim commented on polaris-react/src/components/ResourceList/ResourceList.tsx
> +    <div className={paginationWrapperClassNames}>
```suggestion
    <div className={styles.PaginationWrapper}>
```

2024-02-23 17:29 UTC, laurkim commented on polaris-react/src/components/ResourceList/ResourceList.tsx
> +      <div className={resourceListWrapperClasses}>
```suggestion
      <div className={styles.ResourceListWrapper}>
```

2024-02-23 17:46 UTC, ouellettejordan approved these changes
Tested and all looks and works as expected 👍

2024-02-26 08:52 UTC, mrcthms commented on polaris-react/src/components/Button/Button.module.scss
> +  }
@laurkim Nope, not needed anymore! We have initial designs which used a micro monochrome plain, but have since updated it to be the regular micro button, so I'll remove this 🙌

2024-02-26 10:38 UTC, merged

2024-02-27 22:25 UTC, ecom-integrations commented
Guys seriously make up your mind which direction you are going with this. This is the 3rd major change in recent weeks. The old method of rendering the bulk actions menu over the bottom of the table was the best. Previous version was okay but had issues with CLS and now this new way requires the user to move the mouse pointer to the opposite side of the screen to select the action required. Not a great user experience IMO.