Add responsive viewBox value for mobile
Shopify/polaris-react-archive pull request #11626
Opened 2024-02-21 04:36 UTC by gwyneplaine

### WHY are these changes introduced?

Fixes #0000 

### WHAT is this pull request doing?

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [ ] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2024-02-21 04:36 UTC, gwyneplaine commented
/snapit

2024-02-21 22:14 UTC, gwyneplaine commented
/snapit

2024-02-23 04:10 UTC, gwyneplaine commented on polaris-react/tests/setup/tests.ts
> +// eslint-disable-next-line jest/require-top-level-describe
Since we've added useBreakpoint to the Icon component to affect this mobile resize, we now have more component tests that need matchMedia mocked than otherwise. 

So with that in mind, moving `matchMedia.mock()` and `matchMedia.restore()` calls to the global setup test file when not testing SSR code seemed the right thing to do.

2024-03-04 12:45 UTC, sam-b-rose approved these changes

2024-03-04 16:13 UTC, kyledurand approved these changes
This seems to be working as intended but the icons on small screens look pretty big now. Do we need 👀 from ux / mobile teams on this?

2024-03-04 18:31 UTC, sam-b-rose commented
> Do we need 👀 from ux / mobile teams on this?

Wouldn't hurt! Good suggestion, thanks for the review @kyledurand

2024-03-04 20:25 UTC, aaronccasanova commented on polaris-react/src/components/Icon/Icon.tsx
> +        {...(mdDown ? {viewBox: '2 2 16 16'} : {})}
@sam-b-rose Did you discuss the alternative CSS approach we talked about offline with @gwyneplaine? For transparency, we discussed defining the Icon twice (with different `viewBox` values) and conditionally rendering with CSS e.g.

```tsx
const commonProps = {
  focusable="false"
  aria-hidden="true"
}

return (
  <>
    <SourceComponent
      {...commonProps}
      className={classNames(styles.Svg, styles.SvgMobile)}
      viewBox="2 2 16 16"
    />
    <SourceComponent
      {...commonProps}
      className={classNames(styles.Svg, styles.SvgDesktop)}
    />
  </>
)
```

```css
.SvgMobile {
  display: block;
  @media (--p-breakpoints-md-up) {
    display: none;
  }
}
.SvgDesktop {
  display: none;
  @media (--p-breakpoints-md-up) {
    display: block;
  }
}
```

This would alleviate the need to introduce `useBreakpoints` and the associated test configuration updates.

2024-03-04 20:50 UTC, sam-b-rose commented on polaris-react/src/components/Icon/Icon.tsx
> +        {...(mdDown ? {viewBox: '2 2 16 16'} : {})}
We did discuss this option a bit. I'm not opposed to using the `useBreakpoints` here, however. It does seem to add a lot of boilerplate to our component code by having to introduce this mock on each test, even if the component doesn't use it directly.

The dynamic viewBox solution seems to work well with minimal duplication. Is there a major advantage to using the CSS show/hide solution?

2024-03-04 20:51 UTC, sam-b-rose commented
We plan to follow up this change with a new major of the icons package, changing the viewBox from 20px to 16px

https://github.com/Shopify/polaris/pull/11578

2024-03-05 00:08 UTC, sam-b-rose commented
/snapit

2024-03-05 11:00 UTC, dGoligorsky commented
> > Do we need 👀 from ux / mobile teams on this?
> 
> Wouldn't hurt! Good suggestion, thanks for the review @kyledurand
> 
> Adding @davebcn87 and @dGoligorsky as reviews from the mobile team

Spin link is giving me a 502. I already tried resuming the instance through [Spin Control](https://spin-control.shopify.io/instances/responsive-icons.sam-rose.us.spin.dev). Will try again later ⏳

2024-03-05 20:03 UTC, sam-b-rose commented
@dGoligorsky should be fixed now! Sorry for the spin failure.

I also have it on `staging-ei7k` if you'd rather 🎩 there as well.

2024-03-05 21:29 UTC, aaronccasanova commented on polaris-react/src/components/Icon/Icon.tsx
> +        {...(mdDown ? {viewBox: '2 2 16 16'} : {})}
The main advantages that come to mind are alleviating the need for `useBreakpoints` and the associated test updates. Note: I believe the test updates would also trickles down to consumers. That said, I'm fine to proceed with the current approach.

2024-03-06 09:24 UTC, dGoligorsky requested changes
🎩 — I see the icons on small screens are filling a 20px (1.25rem) box. That makes them too large. I believe we are aiming for nominal 16px box for icons without whitespace. (See this doc for an image with keylines of desktop vs mobile icons.) @heyjoethomas would be great to get your eyes here too.

2024-03-06 17:11 UTC, sam-b-rose commented on polaris-react/src/components/Icon/Icon.tsx
> +        {...(mdDown ? {viewBox: '2 2 16 16'} : {})}
You may be right here. I noticed some issues in the web CI build that was due to breakpoints related to this 🤔 

Good call out—thanks, @aaronccasanova

2024-03-06 22:10 UTC, sam-b-rose commented
/snapit

2024-03-07 02:06 UTC, sam-b-rose commented
@dGoligorsky I've updated the spin link and staging with a new snapshot using SVGs with `viewBox="1 1 18 18"`. This should make the icons closer to 16px in visual size.

2024-03-07 16:30 UTC, dGoligorsky approved these changes
Nice, yeah the updated size (so the icons are nominally 16px) looks more balanced 👍

2024-03-08 11:20 UTC, merged