[Button] Add support for two right direction icons in disclosure prop.
Shopify/polaris-react-archive pull request #11812
Opened 2024-04-01 21:02 UTC by jorgenunezsiri

### WHY are these changes introduced?

Part of https://github.com/Shopify/web/issues/110696

Reasoning: As part of the signup questionnaire in Admin, we have a temporary [DisclosureIconButton](https://github.com/Shopify/guidance-ui/blob/main/src/components/Questionnaire/components/DisclosureIconButton/DisclosureIconButton.tsx#L26) component  that was created as a forked local version of the Button component, to add support for two right direction icons in the disclosure prop:

<img width="750" alt="23-12-2a83e-16gvr" src="https://github.com/Shopify/web/assets/16692690/20e45f75-b496-48fc-aa70-6269886f93cb">

Having these two icons present in the disclosure prop of the `Button` component directly would allow us to simplify this implementation, by removing the previous temporary `DisclosureIconButton` component and using `Button` component for these Admin use cases.

### WHAT is this pull request doing?

This PR adds supports for two right direction icons in Button component disclosure prop: `ChevronRightIcon` and `ArrowRightIcon`, which are used to indicate in-context navigation or navigation to another context, respectively.

#### Results in Storybook

- Arrow right disclosure:
<img width="400" alt="arrow-right-disclosure" src="https://github.com/Shopify/polaris/assets/16692690/ff1b899d-c9b7-4575-b8b1-68b370ab54ce">

- Chevron right disclosure:
<img width="400" alt="chevron-right-disclosure" src="https://github.com/Shopify/polaris/assets/16692690/4772c2c2-9141-4dcd-b688-4a63ef62bd8a">

### How to 🎩

- All Button component tests should pass.
- Storybook displays two new options for disclosure prop in Button component (see results above).

### 🎩 checklist

- [ ] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2024-04-01 23:07 UTC, alex-page requested changes
@jorgenunezsiri the disclosure naming is for creating a popover after a button press. Why can't you do this with an icon in a button?

2024-04-02 11:58 UTC, chloerice commented
> @jorgenunezsiri the disclosure naming is for creating a popover after a button press. Why can't you do this with an icon in a button?

Button.icon puts the icon on the left side of the Button. This is techinically still a disclosure pattern since it opens the next page of a paged Modal, PositionedOverlay is also about to support horizontal position so that Popover can open left/right as well as HoverCard.

2024-04-02 14:07 UTC, heyjoethomas commented
Why wouldn't we do this more generically with something like `iconRight`? That single prop could be used for both instances.

2024-04-02 17:57 UTC, chloerice commented
> I think the ux here could converge into a single option. I don't see a lot of value in a chevron and arrow right option.

+1, the arrow doesn't add clarity in my opinion, where does "I don't want help setting up" navigate? Was there any exploration into a simplified dismissal action in context, like "Skip" or "Dismiss" action?

2024-04-02 21:06 UTC, jorgenunezsiri commented
> Where does "I don't want help setting up" navigate the merchant? Was there any exploration into a simplified dismissal action in context, like "Skip" or "Dismiss"?

@chloerice Thank you for your feedback! There are actually three use cases to consider where we are using the temporary [DisclosureIconButton](https://github.com/Shopify/guidance-ui/blob/main/src/components/Questionnaire/components/DisclosureIconButton/DisclosureIconButton.tsx#L26) component nowadays:
- (1) `Next >` button: The chevron right icon here indicates in-context navigation within the signup questionnaire - similar to how the chevron left icon is presented in the `< Back` button.
- (2) & (3) `I don't want help setting up ->` button / `Get started ->` button: These two buttons use an arrow right to indicate that we are moving away from the signup questionnaire context to the Admin home page context, where you get your home cards, home guides, and home feed.

Please see the video below where I highlight the use cases and also the transitions between the questionnaire cards and from the questionnaire context to the Admin home page context:

https://github.com/Shopify/polaris/assets/16692690/673ca39c-acca-49da-b280-1c9c96143116

> Button.icon puts the icon on the left side of the Button. This is techinically still a disclosure pattern since it opens the next page of a paged Modal, [PositionedOverlay is also about to support horizontal position](https://github.com/Shopify/polaris/pull/11758/files) so that Popover and HoverCard can open left/right. Using UnstyledButton instead would mean copying over hundreds of lines of CSS from Button.css into Web when this is a simple thing that makes sense to support in the system.

@chloerice Yes, this is exactly right. I also agree that this is technically still a disclosure pattern. For the temporary [DisclosureIconButton](https://github.com/Shopify/guidance-ui/blob/main/src/components/Questionnaire/components/DisclosureIconButton/DisclosureIconButton.tsx#L26) component we were able to minimize the styling copy & paste since we are only using the `tertiary` variant for these buttons. But, in the end, it would make sense to support this in the Polaris button for us to decrease maintenance burden in the future. This is because right now the `< Back` button is a Polaris button, but the other questionnaire navigation buttons are not, so if something ever changes in the Polaris side Button implementation in the future, it would need to be manually ported to the other buttons (three cases highlighted above).

2024-05-07 19:22 UTC, closed without merging