Change Banner layout to better align with mobile
Shopify/polaris-react-archive pull request #11887
Opened 2024-04-12 07:30 UTC by mauriciomeirelles

### WHY are these changes introduced?
Fixes https://github.com/Shopify/mobile/issues/33410

### WHAT is this pull request doing?

Implement design from https://www.figma.com/file/PQUFqE9VrOtVPZbaifdL5J/Forms?type=design&node-id=2241-9876&mode=design&t=IEI19PTpbkZdyhKO-0

<img width="997" alt="Screenshot 2024-04-29 at 13 30 36" src="https://github.com/Shopify/polaris/assets/5813840/eba72223-9688-4582-9455-b7719a7ec52c">

Also changes the `success` icon from `CheckIcon` to `CheckCircleIcon`

<img width="317" alt="Screenshot 2024-04-12 at 17 12 40" src="https://github.com/Shopify/polaris/assets/5813840/29865005-4046-47fa-9d8d-a55f5c159f93">

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [x] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2024-04-12 15:17 UTC, mauriciomeirelles commented
/snapit

2024-04-12 19:01 UTC, kyledurand approved these changes
Code and storybook look good. Can you share the spin link when you get a chance?

2024-04-12 19:01 UTC, kyledurand commented on .changeset/neat-bobcats-clean.md
> +Add border to Banner on breakpoint-xs and change success icon to CheckCircleIcon
```suggestion
Added border to Banner on breakpoint-xs and change success icon to CheckCircleIcon
```

2024-04-12 19:01 UTC, kyledurand commented on polaris-react/src/components/Banner/Banner.module.css
> +  margin-inline: var(--p-space-300);
Do we still have to support old mobile safari versions? I thought logical properties were still out because of that. Not a blocker at all. I'm all for using them since it's not task blocking for the long tail

2024-04-15 09:46 UTC, mauriciomeirelles commented
/snapit

2024-04-16 23:20 UTC, heyjoethomas requested changes
Is this being applied to all versions of `Banner`? Also does this change make sure their is 16px of padding between the `Banner` and the edge of the screen?

2024-04-29 11:31 UTC, mauriciomeirelles commented
/snapit

2024-04-29 21:28 UTC, lgriffee commented
Closing in favor of https://github.com/Shopify/polaris/pull/11959 to only apply changes below `sm` breakpoint.

2024-04-29 21:28 UTC, closed without merging