[Icon] add LocationIssue and LocationValid icons
Shopify/polaris-react-archive pull request #11940
Opened 2024-04-24 15:17 UTC by JordanForeman

### WHY are these changes introduced?

resolves https://github.com/Shopify/polaris/issues/11939
resolves https://github.com/Shopify/polaris/issues/11938

### WHAT is this pull request doing?

Adds a new icons to the `polaris-icons` package. 

cc. @ksvihar 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [ ] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2024-04-24 16:25 UTC, sethomas approved these changes
LGTM, might want to wait for a polaris engineer to approve!

2024-04-25 13:47 UTC, sam-b-rose reviewed
Looks good! I've added a commit that cleans up the icon paths using the `optimize` script.

Also a few consistency suggestions to closer match the conventions in other icon YAML files.

2024-04-25 13:47 UTC, sam-b-rose commented on polaris-icons/icons/LocationValidIcon.yml
> +  Education: Used to give merchants information about the validity of the address
```suggestion
description: Used to represent the validity of an address.
```

2024-04-25 13:47 UTC, sam-b-rose commented on polaris-icons/icons/LocationAlertIcon.yml
> +  Education: Used to give merchants information about the invalidity of the address
```suggestion
description: Used to represent the invalidity of an address.
```

2024-04-25 13:47 UTC, sam-b-rose commented on polaris-icons/icons/LocationAlertIcon.yml
> +name: LocationAlert
```suggestion
name: Location alert
```

2024-04-25 13:47 UTC, sam-b-rose commented on polaris-icons/icons/LocationValidIcon.yml
> +name: LocationValid
```suggestion
name: Location valid
```

2024-04-25 14:12 UTC, JordanForeman commented
@sam-b-rose thanks for the suggestions and optimizations! I've incorporated your feedback on the `yml` files :smile:

2024-04-25 22:58 UTC, alex-page commented
@JordanForeman what is the timeline/urgency for these icons? We are building a new icon library to replace this one.

2024-04-25 22:58 UTC, alex-page requested changes
@JordanForeman what is the timeline/urgency for these icons? We are building a new icon library to replace this one.

2024-04-25 23:50 UTC, ksvihar commented
I just realised that the location icons are updated since we first created the icons. So, I just updated the icons and respective issues with to reflect the latest icon designs.

2024-04-26 13:40 UTC, JordanForeman commented
@alex-page I'd say "medium" urgency? We're aiming for mid-May to start using this. I'm not sure we'll have time to include migration to a new icon library, depending on the costs associated with that.

2024-04-26 15:15 UTC, JordanForeman commented
@ksvihar updated! See [0260716](https://github.com/Shopify/polaris/pull/11940/commits/0260716e429394af071936c91efb67af7d5d36e9)

2024-04-28 23:25 UTC, alex-page commented
@JordanForeman is there any blockers or things stopping you from using the icons without polaris-icons until the new library is implemented?

2024-04-29 19:52 UTC, JordanForeman commented
@alex-page nope :smile: I can just hardcode these for now, and we can keep tabs on how icons evolves.

2024-04-29 19:52 UTC, closed without merging