[FormLayout] Ensure Item container width is stable
Shopify/polaris-react-archive pull request #11976
Opened 2024-05-02 21:53 UTC by chloerice

### WHY are these changes introduced?

`FormLayout.Item` currently has an `auto` `flex-basis`, which means when the form initially renders grouped items are equal widths automatically, but individual items are allowed to grow when their content changes instead of maintaining the equal distribution in the available space. For example, a group of two `TextField` components starts out with the item containers being equal, but an item can expand unexpectedly when a `TextField` dynamically has an error message or if one `TextField` has help text and the other doesn't. 

[CodeSandbox reproduction](https://codesandbox.io/p/sandbox/falling-firefly-xmskmx?file=%2FApp.tsx%3A9%2C1) 

### WHAT is this pull request doing?

This PR sets `flex-basis` to `0`, ensuring `FormLayout.Item` has a stable equal width when grouped.

| Before | After |
|--------|--------|
| ![Screenshot 2024-05-02 at 4 21 04 PM](https://github.com/Shopify/polaris/assets/18447883/c4c00c3a-18b3-4060-91aa-0292dd6d3f92)|![Screenshot 2024-05-02 at 4 21 09 PM](https://github.com/Shopify/polaris/assets/18447883/0e9d35a2-854f-4b98-aaad-774082cb91a5) |

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [ ] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2024-05-02 21:58 UTC, chloerice commented
/snapit

2024-05-02 21:59 UTC, chloerice commented on polaris-react/src/components/FormLayout/FormLayout.module.css
> +  flex: 1 1 0;
(This could just be `flex: 1;`, but I prefer it to be obvious what the basis is)

2024-05-06 13:48 UTC, sam-b-rose approved these changes
Changes look good! 💯 

I had to make the code change manullay on the spin instance to get it to work. I think you just need install the snapshot package and restart Vite to get the flex basis changes to appear. It is still using version `13.2.0`.

| Before | After |
| --- | --- |
| <img width="649" alt="before" src="https://github.com/Shopify/polaris/assets/11774595/94402f2a-2e73-4bc5-9fb5-5eb17ee491ef"> | <img width="649" alt="after" src="https://github.com/Shopify/polaris/assets/11774595/272429ed-597a-48c5-8c53-fba839975672"> |

2024-05-06 14:09 UTC, adandach requested changes
@chloerice , I tophatted using your spin instance by testing the form where we initially discovered the issue. It looks like the issue is persisting. To reproduce you can 
1. enable `internal routes` 
2. go to the [Profile Assessment Dev page](https://admin.web.form-layout-item-stable-width.chloe-rice.us.spin.dev/store/shop1/profile-assessment-dev)
3. Select `DE` (Germany) as the country
4. Select `PERSONAL_DETAILS` as the step
5. Enter nonsense as the postal code


https://github.com/Shopify/polaris/assets/5607510/b848aeae-adfc-4db9-a5dc-bfc3b68995c1

2024-05-06 14:31 UTC, adandach approved these changes
After seeing @sam-b-rose 's comment, I tested in my own spin instance and it looks good! 🚀

2024-05-06 16:00 UTC, chloerice commented
Aghhh sorry y'all, thank you @sam-b-rose!

2024-05-06 16:04 UTC, merged