Move reference to unreleased v14 to the v14.0.0 branch
Shopify/polaris-react-archive pull request #12400
Opened 2024-07-16 06:20 UTC by jesstelford

2024-07-16 15:41 UTC, lgriffee requested changes
Typically as soon as a migration is added to our repo we should be providing accompanying guidance even when it's a migration for the next major version. If the issue here is the link then I would suggest that we only remove that one sentence with the link and add it to the v14 branch in the same location.  I think only that should be updated not the removal of this content.

2024-07-16 15:41 UTC, lgriffee commented on polaris.shopify.com/content/tools/polaris-migrator.mdx
> -If you are upgrading Polaris from v13 to v14 please follow our [migration guide](/version-guides/migrating-from-v13-to-v14).
The only line I'd remove here is this one and then make sure to add it to the v14 branch.

2024-07-18 05:45 UTC, jesstelford commented
A good argument well made! I've restored the v14 steps, only removing the link to the non-existent migration guide 👍

2024-07-18 17:04 UTC, lgriffee approved these changes

2025-02-14 03:35 UTC, closed without merging