[WIP] Extend support for split button to ContextualSaveBar and Page
Shopify/polaris-react-archive pull request #2731
Opened 2020-02-07 21:00 UTC by chloerice

### WHY are these changes introduced and WHAT is this PR doing?

As a follow-up to #2329, which added a split variant to `Button`, this PR extends support for this variant to `ContextualSaveBar.saveAction` and `Page.primaryAction` and unblocks https://github.com/Shopify/shopify/issues/214434.  

It also fixes #2688 by wrapping the `Button` in a parent `div` that ensures the style guide playground doesn't cut off the action list.

This is a work in progress because I'm blocked by the current way stacking order is handled by the system. There's currently no accounting for a popover being rendered by an element with a fixed stacking order like the contextual save bar, so the popover of the split button renders below it.

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}

```

</details>

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

2020-02-27 01:17 UTC, chloerice commented on src/components/Button/README.md
> +<div style={{height: '250px'}}>
Adding the wrapper div to fix the playground not being large enough to accommodate the popover.

2020-03-12 14:45 UTC, danrosenthal submitted a review, later dismissed
Code changes make sense to me. You'll need to add code coverage for this line, as it is not being executed in the test environment:

|Code cov|
|-|
|<img width="1270" alt="Screen Shot 2020-03-12 at 10 43 02 AM" src="https://user-images.githubusercontent.com/1403188/76533509-951aa700-644e-11ea-9398-040ff0107252.png">|

You'll also want to look into the accessibility test failure.

2020-11-13 21:18 UTC, chloerice commented on src/components/ContextualSaveBar/README.md
> +          connectedDisclosureAccessibilityLabel: 'Other save actions',
This example overriding default translations was what was causing the aria-label to not work, adding a translation along with the others here fixes it.

2020-11-13 21:57 UTC, chloerice commented
@BPScott I'm not sure how to debug this assertion error in the build tests, have you seen a failure like this before? It seems unrelated to my changes, but it does reference context which this PR does use 🤔

2020-11-26 14:49 UTC, kyledurand requested changes
This PR should be built for web and tested there. Seems like there are some things that have changed since its inception.

I'm also wondering if we should allow both a primary action and split button in both of these components. Especially in Page where the actions are already way too complex than they should be

2020-11-26 14:49 UTC, kyledurand commented on src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
> +        {discardConfirmationModalMarkup}
This has to be moved back out of the ThemeProvider. Otherwise you'll see a dark modal in web

2021-01-29 18:45 UTC, BPScott commented
Removing my review request as I'm moving off the polaris team

2021-12-09 19:44 UTC, closed without merging