Update `Combobox` read.me documentation
Shopify/polaris-react-archive pull request #5321
Opened 2022-03-21 22:43 UTC by sarahill

Updating comobobox documentation for the style guide

2022-03-25 15:42 UTC, jjgali approved these changes
commited changes to fix a typo and a small punctuation thing. Looks great!!

2022-03-25 16:39 UTC, laurkim requested changes
I'd recommend rebasing off main like we did a few times this week to resolve the conflicts:

```
// from combobox-docs-updates branch
git checkout main
git pull
git checkout combobox-docs-updates
git rebase main
git push -f
```

2022-03-25 18:29 UTC, laurkim approved these changes
Nice!! 🚀 👍

2022-03-25 18:59 UTC, merged

2022-03-25 20:40 UTC, chloerice reviewed
Thank you for making these improvements, Sara!! The new format really pushes away from plug-and-play (and hack lol) one-size-fits-all components, toward understanding and leveraging composition for specific merchant needs 🙌🏽 

I've made some suggestions for rewording or simplifying sentences based on our content guidelines ❤️

2022-03-25 20:40 UTC, chloerice commented on polaris-react/src/components/Combobox/README.md
> +Combobox uses an enahnced text field that allows merchants to filter through a list of options to pick one or more values. The list of options is displayed when a merchant focuses on the field.
Since this is only true in some instances (single select, multi-select with previously selected options), should the last sentence be removed and left to the single vs multi select content to explain?

2022-03-25 20:40 UTC, chloerice commented on polaris-react/src/components/Combobox/README.md
> +1. **Text field**: The field people click in to activate the popover and filter through the options they can choose from. Once selected, the option will be shown in the text input.
```suggestion
1. **TextField**: A text input that activates a popover displaying a list of options. As merchants type in the text field, the list of options is filtered by the input value. Options replace or add to the input value when selected.
```

2022-03-25 20:40 UTC, chloerice commented on polaris-react/src/components/Combobox/README.md
> +2. **Popover**: Renders to contain the Listbox.
```suggestion
2. **Popover**: An overlay containing a list of options.
```

2022-03-25 20:40 UTC, chloerice commented on polaris-react/src/components/Combobox/README.md
> +3. **Listbox**: Contains the list of all selectable items.
```suggestion
3. **Listbox**: A list of options to filter and select or deselect.
```

2022-03-25 20:40 UTC, chloerice commented on polaris-react/src/components/Combobox/README.md
> +4. **Listbox** options: The individual options that merchants can select. For context on ways the Listbox can be composed with various content, check out the [listbox documentation](https://polaris.s
```suggestion
4. **Listbox.Option**: The individual options to select or deselect. Check out the [listbox component documentation](https://polaris.shopify.com/components/forms/listbox) to learn how to compose it with various content.
```

2022-03-25 20:40 UTC, chloerice commented on polaris-react/src/components/Combobox/README.md
> +- Be clearly labeled so the merchant knows what type of options will be available
```suggestion
- Be clearly labeled so the merchant knows what kind of options will be available
```

2022-03-25 20:40 UTC, chloerice commented on polaris-react/src/components/Combobox/README.md
> +Allows merchants to select from a predefined list of options. It’s typically used when there are a large number of options to choose from.
```suggestion
Use when merchants can select one option from a predefined or editable list..
```

2022-03-25 20:40 UTC, chloerice commented on polaris-react/src/components/Combobox/README.md
> +Allows the merchant to select multiple options from a pre-defined list of options.
Use when merchants can select one or more options from a predefined or editable list.

2022-03-25 20:40 UTC, chloerice commented on polaris-react/src/components/Combobox/README.md
> +The tag multiselect allows merchants to select, create, and browse from a long list of options.
```suggestion
The tag multi-select input enables merchants to efficiently add or remove tags from a resource like a product or an order. It uses the inline autocomplete combobox pattern to present merchants with an editable list of tags to browse and select from.
```

2022-03-25 20:40 UTC, chloerice commented on polaris-react/src/components/Combobox/README.md
> +Combobox uses an enhanced text field that allows merchants to filter through a list of options to pick one or more values. The list of options is displayed when a merchant focuses on the field.
```suggestion
Combobox is an accessible autocomplete input that enables merchants to filter a list of options and select one or more values.
```

2022-03-25 20:46 UTC, chloerice commented
Doh!! Ignore me 😆  I'm sorry I didn't realize this already shipped, I'd started reviewing this morning and forgot to come back to it until late this afternoon 🤦🏽‍♀️

2022-03-29 19:50 UTC, sarahill commented
No worries I'm happy to circle back and make these updates too. Thanks, Chloe!