polaris-tokens in the monorepo + new token schema
Shopify/polaris-react-archive pull request #5518
Opened 2022-04-12 21:57 UTC by romellogoodman

### WHY are these changes introduced?

Fixes #0000 

We are starting to pull the tokens into more surfaces and thinking about adding more information to the package. The following is an ideation/first pass at pulling the tokens into the monorepo as a separate package with meta data.

Changes
* Creation of @shopify/tokens package
* New schema that allows for the value of the token and its information to be colocated
* Defaulting of colors.light to colors to reduce the amount of boilerplate code needed to access a list of color variables

Next Steps
* Write and export utility functions for working with tokens such as creating the `--p` variable name
* Hook up to the token api since the website won't need to have the package published to consume and use the values
* Publishing to @shopify/tokens package from the monorepo
* Switch over polaris-react to consume @shopify/tokens

2022-04-12 22:12 UTC, alex-page commented on README.md
> +├── polaris-tokens              # Tokens for Polaris
```suggestion
├── polaris-tokens              # Design tokens for Polaris
```

2022-04-12 22:12 UTC, alex-page commented on polaris-tokens/package.json
> +  "version": "1.0.0",
```suggestion
  "version": "5.0.0.rc.1",
```

2022-04-12 22:14 UTC, alex-page commented on polaris-tokens/package.json
> +    "build": "tsc -b",
Not a huge fan of needing to run a build in this directory. @aaronccasanova explored an approach in adding types without a build step for `stylelint-polaris`. I think based on the simplicity here it might be a good approach?

2022-04-12 22:16 UTC, alex-page commented on polaris-tokens/schemas/token-group.json
> +    "figmaName": {"type": "string"}
In my eyes the JSON file should be the simplest format. It then should be ran through some kind of transform for different consumers. I would not expect a `shadow-transparent` to also have to enter in a Figma name of `Shadow transparent`. Could we remove this and generate the name as an output for Figma?

2022-04-13 15:38 UTC, aaronccasanova commented on polaris-tokens/package.json
> +    "test": "npm run validate-tokens",
```suggestion
    "test": "yarn validate-tokens",
```

2022-04-13 15:46 UTC, BPScott commented on polaris-tokens/package.json
> +  "version": "1.0.0",
I'd be `5.0.0-rc.1` for proper semver pre-release tags

2022-04-13 15:46 UTC, BPScott commented on polaris-tokens/package.json
> +  "license": "SEE LICENSE IN LICENSE.md",
There is no LICENCE.md

2022-04-13 15:53 UTC, aaronccasanova commented on polaris-tokens/tokens.ts
> +}
This looks great! Similar to Alex's comment we can likely remove the `figmaName` for now and autogenerate in a build script. (See open-props' [toFigmaTokens transform](https://github.com/argyleink/open-props/blob/a429f931076ab69d3af4539ea312720280cfbdaf/build/props.js#L85-L88))

Also, I do suggest we align our naming with the Design Tokens Glossary as often as possible. In this case I propose updating this type and references to `TokenProperties`: https://www.designtokens.org/glossary/#design-token-properties

2022-04-13 16:02 UTC, aaronccasanova commented on polaris-tokens/token-groups/color.json
> +{
For now, I suggest keeping this `color.light.json` so it's clear these are the `light` color scheme tokens in consuming code. While we don't officially support dark mode we do leverage dark color schemes throughout Polaris and Web. Until we establish next steps for light, dark, and beyond color schemes I think our naming should be very explicit so it's clear how tokens are being used and where to improve.

2022-04-13 16:12 UTC, aaronccasanova commented on polaris-tokens/package.json
> +    "build": "tsc -b",
I have no preference here (: In fact I would have used TypeScript for `stylelint-polaris` if I had more time to resolve ESM/CommonJS issues with the `stylelint` package and deferred to JSDoc to have some type safety. Note: We will still need to run `tsc` in a build step to generate declaration files prepublish, but otherwise TS vs. JSDoc is a matter of preference in this case.

2022-04-13 16:14 UTC, aaronccasanova commented on polaris-tokens/schemas/token-group.json
> +    "figmaName": {"type": "string"}
Agreed, take a peek at open-props' [toFigmaTokens transform](https://github.com/argyleink/open-props/blob/main/build/to-figmatokens.js)

2022-04-13 16:18 UTC, aaronccasanova reviewed
Thanks for kicking this off @romellogoodman! As we've continued to add packages to the monorepo we're starting to feel the pain points of not having a tokens package, so this great timing!!


WIP is looking great 🙌  Left some minor feedback and suggestions

2022-04-13 16:34 UTC, BPScott commented on polaris-tokens/package.json
> +    "build": "tsc -b",
I'd expect that this package should publish a commonjs and and es-modules version, so that it can be both usable within node, and can be easily treeshakable when consumed by bundlers; in addition to shipping types as Aaron mentioned.

Avoiding TS and build steps for stylelint-polaris was fine - it's a node-only package that only needed commonjs output, and it was desirable to write plain js so the in-repo lint run could use the package without needing the package to be built first ("you've got to have a passing build otherwise your linters will crash" would be a bad state of affairs). polaris-tokens is a package that needs to run in both node and browser environments and is expected to be consumed by bundlers too, it's requirements are a bit different to stylelint-polaris

2022-04-14 20:52 UTC, romellogoodman commented on polaris-tokens/tokens.ts
> +}
Updated

2022-04-14 22:47 UTC, aaronccasanova requested changes
Only blocker is the breaking change introduced to the tokens object. The whole system relies on `colorSchemes` right now and would require a major refactor to change that. The fact that we don't have dark mode support doesn't mean we don't have dark UIs. We still have dark UIs and shouldn't start removing elements of the architecture without clear guidance on a path forward imo.

I think the focus of this PR should be to initialize the tokens package so we can start updating all the dependents that have since been doing less than ideal work arounds to consume the tokens (e.g. `polaris-react`, `polaris-for-vscode`, `stylelint-polaris`).

2022-04-14 22:47 UTC, aaronccasanova commented on polaris-tokens/tokens.ts
> +  color: TokenGroup;
```suggestion
  colorSchemes: ColorSchemes;
```

We can challenge these conventions later but as of now the whole system is built off the `colorSchemes` key. Let's please not introduce breaking changes and focus on initializing the tokens package and getting dependents updated to use this lib.

2022-04-14 22:47 UTC, aaronccasanova commented on polaris-tokens/tokens.ts
> +  color: lightColorScheme,
```suggestion
  colorSchemes,
```

Same as above

2022-04-14 22:47 UTC, aaronccasanova commented on polaris-tokens/tsconfig.json
> +    "outDir": "out",
```suggestion
    "outDir": "dist",
```

This was briefly discussed in @samrose3's PR, to configure `tsc` to run from the root, but we should probably settle on an `outDir` naming convention for new libs.

With that said, @samrose3 is there any other `compilerOptions` that need to be set here? If so, we should add a doc about what options to set for libs that do and don't bundle with `tsc`.

2022-04-14 22:47 UTC, aaronccasanova commented on polaris-tokens/token-groups/color.json
> +{
Please revert to `color.light.json`

2022-04-14 23:04 UTC, romellogoodman commented
@aaronccasanova sorry I didnt push latest and had a commit that reverted alot of the color work. I also incorporated the `dist` out folder and removed the `colors` key from the default export

2022-04-14 23:23 UTC, aaronccasanova approved these changes
Awesome work @romellogoodman 🎉 🚀

2022-04-15 12:37 UTC, merged