Enabling custom buttons for page action menu
Shopify/polaris-react-archive pull request #5600
Opened 2022-04-25 14:00 UTC by kemaltatar

### WHY are these changes introduced?

Fixes #0000 

### WHAT is this pull request doing?

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide
- [ ] For visual design changes, ping @ sarahill to update the Polaris UI kit

2022-04-25 14:00 UTC, ghost commented
👋 Thanks for opening your first pull request. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

2022-04-25 14:09 UTC, kemaltatar commented on polaris-react/src/components/ActionMenu/components/SecondaryAction/SecondaryAction.tsx
>    return (
Changed this to div, because when I use a button with Popover, `secondaryActionsRef.current` is initially an empty div with `offsetWidth` of 0. In that case, span cannot calculate the `offsetWidth` from the inner child

2022-04-25 14:12 UTC, kemaltatar commented on polaris-react/src/components/ActionMenu/ActionMenu.tsx
>      <div className={actionMenuClassNames}>
Not a fan of this change but couldn't come up with a better way of doing it. Open to suggestions

2022-04-25 14:13 UTC, kemaltatar commented on polaris-react/src/components/ActionMenu/components/SecondaryAction/SecondaryAction.tsx
> +export function SecondaryActionWrapper({
Separated the wrapper to use the same style and width calculation logic for the custom buttons

2022-04-27 14:57 UTC, alex-page requested changes
@kemaltatar I am unsure about adding a new prop. Specifically the name `customActions` we already have `actions` `rollupActions` `primaryActions` `secondaryActions`.

- Why couldn't you edit existing properties to get this solution?
- Why is the current dropdown not giving you what you need? See [example](https://codesandbox.io/s/gbtbq2?module=App.js) in codepen with popover.

2022-04-27 16:10 UTC, kemaltatar commented
Hey @alex-page , thanks for your feedback!

So if you check [this ticket](https://github.com/Shopify/new-lite-plan/issues/142) you will see that I would need to implement 2 `Popovers` content with conditional rendering and a `Modal` for the same `Button` component. 

Implementing this complicated logic with configurations is unfortunately not possible with the current interface.

Would be happy to pair and show what I mean if you have further questions.

2022-05-17 07:15 UTC, closed without merging