Extract examples out of README files
Shopify/polaris-react-archive pull request #5626
Opened 2022-04-26 19:52 UTC by martenbjork

Quick stab at implementing a solution to https://github.com/Shopify/polaris/issues/5613 .

- Removes code examples from the component Readmes
- Puts them into separate `tsx` files
- Fixes broken example code (adds imports, exports, wrapper functions)
- Adds a json file with descriptions of each example

This is a one-time extraction. After this point, we can make subsequent improvements like running prettier over the examples.

2022-04-26 20:26 UTC, martenbjork commented on polaris-react/src/components/ButtonGroup/examples/outline-button-group-with-segmented-buttons.tsx
> +  );
A Prettier run is needed 😊

2022-04-26 20:33 UTC, alex-page requested changes
This is great but would break the styleguide. We need to commit to archiving the existing one or think of a backwards compatible solution.

2022-04-26 20:39 UTC, martenbjork commented
> This is great but would break the styleguide. We need to commit to archiving the existing one or think of a backwards compatible solution.

Oof, true. We could keep the examples in the Readme for now. That would allow the next.js website to use this new file structure for a time and then, when we're ready to remove the styleguide, we re-run the script, including the part that removes the examples from the readme.

2022-04-26 20:41 UTC, alex-page commented
My thought is...

1. Ship new site with existing shitty structure
2. Replace old site
3. Fix this up and make best examples ever?

2022-04-26 20:42 UTC, martenbjork commented
Yeah, I'm OK with that! 👍

2022-05-31 12:59 UTC, sam-b-rose commented
@martenbjork should we go ahead and close this one out?

2022-05-31 13:09 UTC, romellogoodman commented
@samrose3 , i think it cool to close in favor of #5940

2022-05-31 13:23 UTC, closed without merging