[Listbox] Fix: preserve scroll position when lazy-loading additional items
Shopify/polaris-react-archive pull request #5812
Opened 2022-05-14 00:45 UTC by developit

This fixes a regression in `@shopify/polaris` at version `9.4.0-rc.1`. Previously, appending additional items to a Listbox would preserve the current scroll position. Additional focus management was added (I believe in #5303) that may not have accounted for this case.

Fixes #5809.

### WHY are these changes introduced?

Fixes #5809 (see issue for details from @gcrevell)

### WHAT is this pull request doing?

It Listbox from being scrolled to the top via `scrollIntoViewIfNeeded` when items are appended to the current list of items. The focus behaviour for changing or removing items is unchanged.

#### Before:

https://user-images.githubusercontent.com/105127/168404342-befd7766-ee7c-4a36-81a1-76cc013e215f.mov

#### After:

https://user-images.githubusercontent.com/105127/168404393-65a1c3db-85dc-477b-abfc-8ff96c861709.mov

2022-05-14 00:45 UTC, ghost commented
👋 Thanks for opening your first pull request. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

2022-05-16 14:26 UTC, gcrevell commented
I like the changes you made, and they make sense to me at least. Some tests would be nice though! Need to prevent regressions 😁

2022-05-16 19:27 UTC, alex-page commented
@developit thanks a ton for this contribution. Chloe and Lo are out this week and I would love their eyes on this.

Is there any urgency on getting this fixed? I am unsure of the complexity of adding a test but it would be greatly appreciated.

2022-05-16 21:10 UTC, developit commented
@alex-page hi - not urgent, was just a fix for an issue raised in Slack.

2022-05-24 18:57 UTC, laurkim commented
@developit fyi, since this PR was created, the Polaris team has moved away from entries in an `UNRELEASED.MD` file in favor of changesets. I created and pushed up the changeset in this [commit](https://github.com/Shopify/polaris/pull/5812/commits/a7a3d100634561102548bd4f8435a32ac4b23c8c)

2022-05-24 19:37 UTC, laurkim requested changes
The code does fix the regression of the scroll position jumping to the top when lazy loading additional items, but breaks keyboard navigation where you cannot arrow up/down through the additional items. Video example below where after the next batch of items loads, I navigate down from first item to get to `Rustic 26` using arrow keys.


https://user-images.githubusercontent.com/26749317/170118051-fa811f1e-0cfc-490f-bdac-32de6ed57c6b.mp4

Happy to pair on this together if you'd like 👍

2022-06-01 01:54 UTC, developit commented
I'm not an accessibility expert, but is the right thing to do here really to change the focused item when scrolling with the mouse wheel?

2022-06-02 16:16 UTC, chloerice commented
> I'm not an accessibility expert, but is the right thing to do here really to change the focused item when scrolling with the mouse wheel?

Hey @developit this is a known issue that is not priority at this time because autocomplete implementations should prioritize search over endless scroll. I don't have capacity right now, but I'll have a free cycle to dig into your PR in a couple of weeks (I think you're onto the right fix, it just currently breaks keyboard navigation so would be trading one bug for another and keyboard is higher priority in autocomplete UX).

2022-06-02 16:24 UTC, developit commented
Thanks @chloerice!

2022-06-03 15:42 UTC, laurkim commented
@developit I dug around a little more and it turns out the reason keyboard navigation wasn't working as expected was because the `currentOptions` weren't being updated to include the next set of options. When trying to fix it, it was causing an infinite loop of refreshing options so I had to separate out the logic for when the list is unchanged and when it's appended. I made a PR based off your branch [here](https://github.com/Shopify/polaris/pull/6025).

cc @chloerice

2022-06-03 15:45 UTC, laurkim commented on .changeset/curvy-rockets-provide.md
> +Fixed Listbox to preserve scroll position when lazy-loading additional items
```suggestion
'@shopify/polaris': patch
---

Fixed `Listbox` to preserve scroll position when lazy-loading additional items
```

2022-06-06 13:26 UTC, laurkim commented
/snapit

2022-06-06 15:00 UTC, laurkim approved these changes

2022-06-06 15:16 UTC, chloerice approved these changes
🚀

2022-06-08 18:36 UTC, merged