[Page] Fix page without header section causes scroll
Shopify/polaris-react-archive pull request #5928
Opened 2022-05-25 13:36 UTC by FCalabria

### WHY are these changes introduced?

When a `Page` component does not have any attribute that generates a `Header`, the content adds some margin to create a proper separation to the top of the page. That separation is created with a margin (contrary to the header, which uses padding to create that space) which affects the `body` position and creates an undesired scroll.

<details>
      <summary>Bug reproduction on the playground</summary>
      <img src="https://screenshot.click/25-09-5q3ay-wp6gs.gif" alt="canvas section off the playground, empty except for a text 'Page with no header section'. The page scrolls slightly up and down ">
    </details>

### WHAT is this pull request doing?

Changed the margin by padding so it doesn't affect the body position.

Before:
![playground, the body element of the canvas is selected with the element inspector. A red arrow points to a space left between the body and the top of the page. At the bottom, the body overflows the canvas](https://screenshot.click/25-25-nhhhj-g1n5q.png)

After:
![playground, the body element of the canvas is selected with the element inspector. It fits the canvas area perfectly](https://screenshot.click/25-27-9cr6m-c3ltj.png)

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2022-06-27 15:47 UTC, FCalabria commented
/snapit

2022-06-27 17:30 UTC, kyledurand requested changes
I'm not sure this is the best fix for the issue. Looks like we might have been relying on margin collapses and this change will introduce new spacing. I could be wrong but I'd love to see a spin instance with the snap before approving

2022-06-28 10:02 UTC, FCalabria commented
@kyledurand yeah sure, here you have a spin with the snapshot installed on web: https://web-66hm.paqui-calabria.eu.spin.dev/
I have checked side by side pages with title, without title and with `title=""` and all looks good to me, but I might have overlooked some corner case.

2022-06-29 13:39 UTC, kyledurand approved these changes
🎩  in spin looks good to me 👍

2022-06-29 16:14 UTC, chloerice approved these changes
Tophat looks good to me as well! 👀

2022-06-29 16:14 UTC, chloerice commented on .changeset/shy-suns-peel.md
> +Fix scroll caused by Page without header section
```suggestion
Fixed  `Page` without header section causing unnecessary scrollbar
```

2022-06-30 07:45 UTC, FCalabria commented
/shipit

2022-06-30 15:16 UTC, merged