[TokenList] Add copy/paste tooltip for tokens v1
Shopify/polaris-react-archive pull request #5959
Opened 2022-05-26 21:30 UTC by chazdean

### WHY are these changes introduced?

Fixes [#5902](https://github.com/Shopify/polaris/issues/5902)

Currently there is no quick way for users to copy tokens directly from the webpage.

### WHAT is this pull request doing?

Adds a clipboard icon next to the token name, which when clicked copies the token to the user clipboard along with showing a tooltip with the action status.

<details>
<summary>
After — feature implemented
</summary>
</details>

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2022-05-27 07:12 UTC, martenbjork commented
Looks great! 🚀 I added some minor comments.

2022-05-27 12:49 UTC, martenbjork requested changes

2022-05-27 12:49 UTC, martenbjork commented on polaris.shopify.com/src/components/TokenList/TokenList.tsx
> +);
This shady way of importing icons is only used when we need to iterate over *all* of the icons (like the icons page). For normal use cases, I would just chuck the svg I need into the component folder and import it like so:

```
import clipboardIcon from "./ClipboardMinor.svg";

<Image src={clipboardIcon} ... />
```
You can also put images in the `public` folder if you feel like that makes more sense.

2022-05-27 12:49 UTC, martenbjork commented on polaris.shopify.com/src/components/TokenList/TokenList.tsx
> +            <div className={styles.TokenToolTipImage} onClick={()=>copy()}>
When you're calling a function with no parameters, React lets you do this:

`onClick={copy}` which is the exact same thing as `onClick={() => copy()}`

2022-05-27 12:49 UTC, martenbjork commented on polaris.shopify.com/src/components/TokenList/TokenList.module.scss
> +}
Github complains about no newline at the end of the file. It's a popular convention for some reason.

Are you using Prettier in VS Code with "format on save"? That should add a newline automatically every time you save.

2022-05-27 12:49 UTC, martenbjork commented on polaris.shopify.com/src/components/TokenList/TokenList.module.scss
> +  filter: brightness(1.25);
You might consider going into the svg and setting the color you want in there. That way you don't have to run `filter` on a bunch of images. Removes a liiittle work for the browser.

2022-05-27 18:45 UTC, romellogoodman commented on polaris.shopify.com/src/components/TokenList/TokenList.module.scss
> +}
Formatting has been disable for the entire project. I just opened #5969 to restore it.

2022-05-27 18:46 UTC, romellogoodman commented on polaris.shopify.com/src/components/TokenList/TokenList.tsx
> +  const [copy, didJustCopy] = useCopyToClipboard(`--p-${name}`);
A small nit: Consider creating a variable for `--p-${name}` and referencing it both here and in the h4 below. Would help keep the values in sync in the long run.

2022-05-30 13:23 UTC, chazdean commented on polaris.shopify.com/src/components/TokenList/TokenList.tsx
> +            <div className={styles.TokenToolTipImage} onClick={()=>copy()}>
👍🏾

2022-05-30 13:24 UTC, chazdean commented on polaris.shopify.com/src/components/TokenList/TokenList.tsx
> +);
Thats good to know!

2022-05-30 13:26 UTC, chazdean commented on polaris.shopify.com/src/components/TokenList/TokenList.module.scss
> +}
I installed Prettier, and it seems to be working 👍🏾

2022-05-30 13:26 UTC, chazdean commented on polaris.shopify.com/src/components/TokenList/TokenList.tsx
> +  const [copy, didJustCopy] = useCopyToClipboard(`--p-${name}`);
Thats a good idea!

2022-05-30 13:29 UTC, chazdean commented on polaris.shopify.com/src/components/TokenList/TokenList.module.scss
> +  filter: brightness(1.25);
Good call 👍🏾

2022-05-31 16:14 UTC, romellogoodman approved these changes
lgtm! 👏🏿

2022-05-31 21:15 UTC, martenbjork approved these changes
Awesome! 🚀

2022-06-22 19:22 UTC, closed without merging