[ActionList] Includes export of ActionListItem
Shopify/polaris-react-archive pull request #6005
Opened 2022-06-01 20:48 UTC by felipeleusin

### WHY are these changes introduced?

In Shopify Email we have a situation where we use the ActionList with just a single item. When we built this a while ago we had to resort to an override of Polaris CSS but as polaris evolved our hack broke. We actually don't need any of the features of the ActionList and would just like to be able to re-use the ActionList item directly, the other option would be copy the implementation of the component but I'd rather not do that.

This PR simply include the ActionListItem as an export of polaris, so that it can be used directly outside an ActionList.

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2022-06-02 14:54 UTC, alex-page requested changes
@felipeleusin we strongly recommend not overriding these custom properties. We are tracking folks using them in shopify/web. Do you have to use an ActionList component, could you use a stack instead?

2022-06-02 14:56 UTC, felipeleusin commented
> @felipeleusin we strongly recommend not overriding these custom properties. We are tracking folks using them in shopify/web. Do you have to use an ActionList component, could you use a stack instead?

Stack doesn't work, we actually care less about ActionList and more about the ActionListItem, if we could use just the ActionListItem but they are wrapped in an `li`. Sadly it seems like the solution would be to create a custom component for this, which I was trying to avoid

2022-06-02 14:57 UTC, alex-page commented
@felipeleusin can you provide some screenshots and context of what you are trying to create? Or a codesandbox?

2022-06-20 13:32 UTC, felipeleusin commented
Replaced by https://github.com/Shopify/polaris/pull/6229

2022-06-20 13:32 UTC, closed without merging