[polaris.shopify.com] Polish contribution guidance
Shopify/polaris-react-archive pull request #6430
Opened 2022-06-28 15:32 UTC by chloerice

### WHY are these changes introduced?

This PR: 
- Fixes `Layout` adding extra left and right content padding on small screens
- Adds a background to inline code snippets
- Polishes contribution guidance content
- Adds a hook for setting query params, to be used in a follow up PR to make component examples linkable

### WHAT is this pull request doing?

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

- `git checkout quickstart-table_concept-1`
- `yarn build && yarn turbo run dev --filter=polaris.shopify.com`
- Navigate to `localhost:3000/contributing`
- Things to look for in the /contributing section:
  - Broken or missing links
  - Typos
  - etc 

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2022-07-01 00:36 UTC, chloerice commented on polaris.shopify.com/src/components/Layout/Layout.module.scss
> +    padding: 0;
This fixes small screen being doubled up, as `Container` also adds `1rem` of padding.

2022-07-01 00:38 UTC, chloerice commented on polaris.shopify.com/src/components/Longform/Longform.module.scss
> +    p {
Ensures paragraphs rendered in tables don't have longform content level spacing.

2022-07-05 14:10 UTC, chloerice commented on polaris.shopify.com/src/components/Longform/Longform.module.scss
> +  code {
(This adds styles for inline code snippets)

2022-07-05 15:07 UTC, chloerice commented on polaris.shopify.com/src/components/QuickStartGuide/QuickStartGuide.tsx
> +    setQueryParams({ quickGuide: `${queryParamValues[Number(nextIndex)]}` });
@martenbjork When I'm back from holiday I'll put up a PR to add query params to examples so folks can link to a specific example too 😁

2022-07-05 20:22 UTC, alex-page commented
The content and direction this work is headed in is awesome.

I was a bit unsure the value we from some of the design decisions it felt like we were shipping a data structure. I also think the user experience could be pushed and evolved easier with a simpler approach.

1. The drop down switcher hides quick start guides and requires users to press them to see them. Users should be able to see all quick start guides without clicking a button.
2. Quick start guides don't get a lot of value from the table layout. They could be simplified to be markdown pages with heading structure.
3. The complexity of sharing these with them being a part of a select instead of a table isn't high value. Having to update query params isn't great.
4. Future quick start guides have to follow this structure and flexibility might be useful to make guides the best they can be for our users.

2022-07-05 22:36 UTC, chloerice commented
> The content and direction this work is headed in is awesome.
> 
> I was a bit unsure the value we from some of the design decisions it felt like we were shipping a data structure. I also think the user experience could be pushed and evolved easier with a simpler approach.
> 
> 1. The drop down switcher hides quick start guides and requires users to press them to see them. Users should be able to see all quick start guides without clicking a button.
> 2. Quick start guides don't get a lot of value from the table layout. They could be simplified to be markdown pages with heading structure.
> 3. The complexity of sharing these with them being a part of a select instead of a table isn't high value. Having to update query params isn't great.
> 4. Future quick start guides have to follow this structure and flexibility might be useful to make guides the best they can be for our users.

Thanks for this detailed feedback @alex-age!! 🙌🏽 

The goal with this design was to simplify the [initial table concept](#6430) we drafted in the Google Doc by reusing the pattern used for component examples because it's:
- A pattern that consumers and contributors are used to that doesn't take up massive real estate on the page
- Allows the guidance to scale regardless of how many ways there are to contribute (illustrations: 1, documentation: 4)
- Cuts the redundancy of the content, as there's a lot of the same answers across contribution types
- Makes the framing of Who/What/Where/When/How info more human 
- Presents the info in a scannable format (inspired by breakout tables in textbooks 📚) in order to: 
  - Minimize overwhelm for new contributors
  - Speed up existing contributors 
  
The query params aren't needed for the select, they're prep for exploring the idea mentioned in the last bullet of the PR description. They're also there to make linking to relevant guidance more direct when supporting folks in Slack and on GitHub. It's also something I've been wanting to contribute to component examples forever for the same reason.

The data coming from frontmatter vs from within the Mardown wasn't the initial plan, but was what I landed on to move quickly because we can't parse the individual parts of the table from ReactMarkdown (at least not from what I tell). It's def not ideal, but I also don't think it should block shipping the MVP of the guidelines. We plan on making fast follows in the coming weeks to elevate the design of these pages to the level of the rest of the site. This feedback will be super useful as we iterate, especially now that we're gonna have a designer helping with this work (yaaay @raquelbreternitz 🎉).

2022-07-06 15:10 UTC, alex-page commented
That all makes sense @chloerice. My thought with markdown was to remove the table all together. I think the table is limiting and increasing complexity.

2022-07-11 14:48 UTC, chloerice commented on polaris.shopify.com/content/contributing/illustrations.md
> +This is a placeholder table, quick start guides render here. You can find and edit quick guide content in the metadata (front matter) at the top of this file. The placeholder table is here so the Mar
> That all makes sense @chloerice. My thought with markdown was to remove the table all together. I think the table is limiting and increasing complexity.

@alex-page I think what you're referring to are [the Markdown tables from the PR this replaces](https://github.com/Shopify/polaris/pull/6398/files#r918024958)? We don't hold the content in that format anymore. The content lives in the front matter of each `/contributing` file, which gets passed to the `QuickStartGuide` component.

2022-07-12 19:25 UTC, selenehinkley approved these changes

2022-07-12 19:59 UTC, alex-page commented on polaris.shopify.com/content/contributing/documention.md
> +        answer: <a href="/contributing/shipping-your-contribution">Open a pull request</a> in the <a href="https://github.com/Shopify/polaris">Shopify/polaris</a> GitHub repo
This approach to content is complex and should be avoided. I think we can create a much simpler initial solution that is just a HTML page. I am unsure what value the `QuickStartGuide.tsx` component is giving.

2022-07-12 20:01 UTC, alex-page requested changes
The approach to quick guides content is complex and should be avoided across the website. We should create a much simpler initial solution that is just a HTML page using markdown and title hierarchy. I don't think the effort to maintain the frontmatter, parsing, QuickStartGuide.tsx etc. is worth the outcome for our users.

2022-07-12 20:03 UTC, alex-page commented on polaris.shopify.com/content/contributing/illustrations.md
> +This is a placeholder table, quick start guides render here. You can find and edit quick guide content in the metadata (front matter) at the top of this file. The placeholder table is here so the Mar
I added a comment to add some clarity below.

2022-07-13 14:41 UTC, yurm04 commented
I agree with all the things you've brought up @alex-page , but we also want to ship this quickly since we’re still iterating on the design of all the guidelines, and the quick start table was the most difficult to come up with a great design on a tight deadline with no UXers. This does add more tech debt to the site right now but @raquelbreternitz  and @chloerice are going to be revisiting the design asap. Since all of these changes are contained they can be easily ripped out at that point. ATM I would consider this page a `Blocker for comms` and should be resolved before the website project end date. Until then, we need this page quickly to unblock internal comms so that we can start getting feedback from Shopifolk and collaborating with teams to contribute pattern guidance for another project

2022-07-13 17:45 UTC, alex-page approved these changes
Approving. I don't feel great about the added technical debt for adding what should be simple pages. I will create a follow up PR to remove a bunch of unnecessary code.

2022-07-13 21:45 UTC, yurm04 approved these changes

2022-07-13 22:37 UTC, merged