[polaris.shopify.com] Various a11y improvements
Shopify/polaris-react-archive pull request #6473
Opened 2022-07-01 22:31 UTC by chloerice

### WHY are these changes introduced?

Closes #6469, #6470, and #6471

- General:
  - Gave light mode --surface-subdued analgous weight to dark mode
- Icons: 
  - Made the icon name button text responsive and accessible
- Home Page:
  - Render an image in place of video if reduce motion preference is set in the Polaris for VS Code section

### WHAT is this pull request doing?

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2022-07-04 08:16 UTC, gui-santos requested changes
This is great! 🙌 

I had only a few questions and suggestions 🙏

2022-07-04 08:16 UTC, gui-santos commented on polaris.shopify.com/src/components/HomePage/HomePage.module.scss
> +    max-width: 65.5%;
The `min-width` here is missing the `%` sign

And I have another question, I see that both min- and max-width have the same value 65.5% which is bigger than the `width` value. So I think that in the end they are not doing anything
Isn't it possible to remove them and keep only `width` in this case?

And I think the margin-right is also not doing anything. At least, it seems not to do anything when I checked in Chrome's inspector

2022-07-04 08:16 UTC, gui-santos commented on polaris.shopify.com/src/components/HomePage/HomePage.tsx
> +  console.log(useMotion);
Is this a leftover?

I also forget to remove console.logs in this project and I think it's because the eslint has no rules in `polaris.shopify.com`

2022-07-04 08:16 UTC, gui-santos commented on polaris.shopify.com/src/components/HomePage/HomePage.tsx
> +import { useMediaQuery } from "@shopify/polaris/build/ts/latest/src/utilities/media-query";
I think this is not being used anywhere, is it?

2022-07-04 08:16 UTC, gui-santos commented on polaris.shopify.com/src/components/HomePage/HomePage.module.scss
> +      // position: relative;
Should this be removed, maybe?

2022-07-04 17:33 UTC, martenbjork commented on polaris.shopify.com/src/pages/api/v0/tokens/index.tsx
> +<html lang="en">
This HTML is actually for the scrappy landing page for the API.

To add the lang attriibute for all pages, you can add some shenanigans to next's config file, see #6475 .

2022-07-04 17:37 UTC, martenbjork commented on polaris.shopify.com/src/styles/globals.scss
> +  --surface-inline-code: #e7e7e7;
Is this used somewhere? 🧐

2022-07-04 17:39 UTC, martenbjork commented on polaris.shopify.com/src/components/IconGrid/IconGrid.module.scss
> +    color: var(--text);
Thanks for removing that hard coded text color! A leftover from prototyping...

I wonder if we could use text-subdued for these, if we upped text-subdued to `#767676`?

<img width="256" alt="image" src="https://user-images.githubusercontent.com/875708/177199532-ef63a8b2-843f-4e37-aeb2-c96e94e9170c.png">

2022-07-04 17:40 UTC, martenbjork requested changes
Thanks for fixing these issues! 🔥

2022-07-05 14:12 UTC, chloerice commented on polaris.shopify.com/src/styles/globals.scss
> +  --surface-inline-code: #e7e7e7;
Ah yes! This PR actually started off as part of [this other PR](https://github.com/Shopify/polaris/pull/6430/files#r913845615) and I broke it out because it kind of spiraled as I started doing a11y testing 😅 Moved `--surface-inline-code` to #6430

2022-07-05 14:35 UTC, chloerice commented on polaris.shopify.com/src/components/HomePage/HomePage.module.scss
> +      // position: relative;
🙏🏽

2022-07-05 16:02 UTC, gui-santos approved these changes
Looks good! 💎

2022-07-05 20:03 UTC, martenbjork approved these changes
Fantastic 🔥🔥

2022-07-05 20:03 UTC, martenbjork commented on polaris.shopify.com/src/components/HomePage/HomePage.tsx
> +                    className={styles.Poster_Image}
Nit: For classes, we use `ThisCasingWithoutUnderScores` in the rest of the project.

2022-07-05 20:03 UTC, martenbjork commented on polaris.shopify.com/src/components/HomePage/HomePage.tsx
> +import vsCodeImage from "./vscode.png";
This single asset weighs in at 3.4mb. Simply exporting it as a JPEG reduces the size by 90%.

Next/Image will serve a compressed version, so users won't suffer, but converting it might be a tiny win towards keeping the repo lightweight...er.

2022-07-05 22:51 UTC, merged