[DataTable] Various Improvements
Shopify/polaris-react-archive pull request #6532
Opened 2022-07-07 14:31 UTC by philschoefer

### WHY are these changes introduced?

Fixes #0000 

### WHAT is this pull request doing?

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2022-07-12 15:47 UTC, ErickTamayo approved these changes
LGTM

2022-07-12 16:07 UTC, blboyle commented
https://screenshot.click/12-06-xm8k6-4eol8.mp4

@philschoefer @JeremyLudwigDev 

The headings move back and forth from sticky to non-sticky, but the navigation ones do not.

2022-07-12 18:41 UTC, blboyle commented
https://screenshot.click/12-39-zu9v4-wu9n4.mp4

This is what it looks like for keyboard focusing when you combine the fixed first column and header.

2022-07-13 19:52 UTC, blboyle approved these changes

2022-07-14 17:11 UTC, blboyle commented
There are a few things that could be cleaned up in followup (as per our chat regarding the first column) but this looks great to get out in order to fix that error. 👍🏻

2022-07-14 17:11 UTC, blboyle approved these changes

2022-07-14 17:18 UTC, ErickTamayo requested changes

2022-07-14 17:18 UTC, ErickTamayo commented on polaris-react/src/components/DataTable/DataTable.tsx
> +    const navigationMarkup = (location: 'sticky' | 'header') =>
I think this can be wrapped into a `useCallback` and wrap both calls inside a `useMemo`


```js
const stickyMarkup = useMemo(() => navigationMarkup('sticky'), [navigationMarkup])
const headerMarkup = useMemo(() => navigationMarkup('header'), [navigationMarkup])
```

2022-07-14 17:18 UTC, ErickTamayo commented on polaris-react/src/components/DataTable/DataTable.tsx
>      const stickyHeaderMarkup = stickyHeader ? (
This should be wrapped inside a `useMemo`

2022-07-14 18:26 UTC, JeremyLudwigDev commented on polaris-react/src/components/DataTable/DataTable.tsx
> +    const navigationMarkup = (location: 'sticky' | 'header') =>
This won't work since we can't use hooks in a class component.

2022-07-14 19:05 UTC, ErickTamayo approved these changes

2022-07-15 12:49 UTC, merged