[polaris.shopify.com] Home page: "Polaris for VS Code" section looses background on smaller breakpoints
Shopify/polaris-react-archive pull request #6674
Opened 2022-07-19 18:13 UTC by adrianefong

Fixes Polaris VS Code section on the homepage.

**Before**
Subdued background was not showing up in mobile and desktop breakpoints. 

https://user-images.githubusercontent.com/97708939/179819855-a62753a4-096d-481a-83e2-7d2789225967.mp4

**After**
Subdued background is showing up and is consistent with other sections. 

https://user-images.githubusercontent.com/97708939/179820210-6f4cbfbb-3c96-4b77-85d8-4076f6bc0b13.mp4

2022-07-19 18:20 UTC, martenbjork approved these changes
Ooof, nice catch! 🚢 🚀

2022-07-19 18:25 UTC, martenbjork requested changes
Hmm, it looks like this fix inadvertently adds a bit of padding to the VSCode block.

I think this bug could be fixed by keeping the JSX/HTML same as today, but removing `background: transparent` from line 306 in `HomePage.module.scss`. https://github.com/Shopify/polaris/blob/main/polaris.shopify.com/src/components/HomePage/HomePage.module.scss#L306

2022-07-20 07:13 UTC, martenbjork approved these changes
Looks great! Thanks for the padding fix as well.

Now this just needs a `changeset` which is an entry for the changelog. Instructions can be found here: https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#adding-a-changeset

Let me or anyone else on the team know if you run into any problems! 🚀

2022-07-20 20:54 UTC, adrianefong commented
@martenbjork just added the changeset! does it look okay?

2022-07-20 22:02 UTC, merged

2022-07-20 22:03 UTC, martenbjork commented
Looks perfect! Merged! 🚀🚀