[IndexTable] Reduce offset to fix overlap
Shopify/polaris-react-archive pull request #7433
Opened 2022-10-18 14:43 UTC by kellymiller-shop

### WHY are these changes introduced?

Fixes #0000 

### WHAT is this pull request doing?

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2022-10-18 14:43 UTC, kellymiller-shop commented
/snapit

2022-10-18 16:21 UTC, alex-page approved these changes
I haven't tested but code and screenshot look great to me. If you haven't just double check mobile web. 🚀 

Thank you @kellymiller-shop

2022-10-19 14:21 UTC, AndrewMusgrave requested changes
Looks like there may be a problem on mobile - I don't see the bulk header at all 😬

2022-10-19 15:14 UTC, voiid commented
@AndrewMusgrave this is currently an issue on prod..

2022-10-19 16:21 UTC, AndrewMusgrave commented
@voiid I noticed that as well :(

2022-10-19 16:29 UTC, AndrewMusgrave commented
Put up a fix [here](https://github.com/Shopify/polaris/pull/7453)

2022-10-19 16:30 UTC, AndrewMusgrave approved these changes
LGTM ✅

2022-10-19 16:42 UTC, merged