[feature] Adds `blurOnEnterKeyPress` to programmatically trigger blur events
Shopify/polaris-react-archive pull request #7608
Opened 2022-11-01 23:11 UTC by QuintonC

### WHY are these changes introduced?

In some cases we want to allow users to press "enter" on their keyboard when inputs do not have a "submit" button. Consider a modal similar to the App Bridge `ResourcePicker` which has an input albeit no "enter" or "submit" button. That is because the input searches as the user types their query into the input. 

However, in the event that we only want to run a query when the user blurs their input (via `onBlur`) by clicking out of focus, tabbing out, or by pressing `Enter` on their keyboard. This PR adds the `blurOnEnterKeyPress` prop as an optional boolean that programmatically blurs the input via the `inputRef`, thus triggering unfocusing the input and triggering the `onBlur` callback (if defined).

### WHAT is this pull request doing?

<details>
  <summary>Video example</summary>

  https://user-images.githubusercontent.com/4250423/199359141-bdd531d8-34b6-4384-b1e4-2e1fbaa549b5.mov

</details>

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

Using storybook, open the TextField component and navigate to the `With Blur On Enter` example. Pressing `enter` while the input is focused will trigger the callback which displays a Toast.

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2022-11-01 23:36 UTC, QuintonC commented
/snapit

2022-11-09 03:50 UTC, QuintonC commented
This is being used actively in https://github.com/Shopify/gm-shop-merchant-app.  I'd be happy to look into other suggestions if any are presented.

I had considered forwarding a `ref` to `TextField`, but after speaking with @kyledurand I was informed of [this discussion](https://github.com/Shopify/polaris/issues/521#issuecomment-424755928), which makes it seem like we do not want to expose any synthetic events or refs.

2023-04-14 03:12 UTC, QuintonC commented
/snapit

2023-04-14 03:13 UTC, QuintonC commented
Making a note for the folks who are going to review this that I will be dropping a spin link where you can test this in Slack 👍

2023-04-16 23:03 UTC, alex-page requested changes
I am confused by the outcome of this PR. It's too specific in my opinion "blurOnEnterKeyPress". I don't see the value in this specificity rolling out to every `<TextField>` in the admin.

2023-04-17 13:43 UTC, chloerice reviewed
Hey Quinton 👋🏽 I agree with Alex that this prop would be too specific to your use case. You can accomplish what you need to for your use case by adding support for setting a keypress callback. I know of several cases where handling key press of Enter is done by the wrap-it-in-a-div event handling method, which feels unnecessary. We should support setting the handler directly.

2023-04-17 13:43 UTC, chloerice commented on polaris-react/src/components/TextField/TextField.tsx
> +  blurOnEnterKeyPress?: boolean;
```suggestion
/** Callback fired on key press */
  onKeyPress?(event: React.KeyboardEvent): void;
```

This would be best as a general callback. You can programmatically set `focused` to false or do whatever else you need to if the key pressed is Enter using the callback.

2023-04-17 13:43 UTC, chloerice commented on polaris-react/src/components/TextField/TextField.tsx
> +  blurOnEnterKeyPress,
```suggestion
  onKeyPress,
```

2023-04-17 13:43 UTC, chloerice commented on polaris-react/src/components/TextField/TextField.tsx
> +    }
```suggestion
    if (onKeyPress) {
      onKeyPress(event)
      return;
    }
```

2023-04-17 14:26 UTC, QuintonC commented
> I am confused by the outcome of this PR. It's too specific in my opinion "blurOnEnterKeyPress". I don't see the value in this specificity rolling out to every `<TextField>` in the admin.

> Hey Quinton 👋🏽 I agree with Alex that this prop would be too specific to your use case. You can accomplish what you need to for your use case by adding support for setting a keypress callback. I know of several cases where handling key press of Enter is done by the wrap-it-in-a-div event handling method, which feels unnecessary. We should support setting the handler directly.

@alex-page @chloerice Hey, thanks for the feedback!

I greatly appreciate you both taking a look at it. 

Ideally, yes, `onKeyPress` would be the preferred way to do this. However, when I spoke with @kyledurand back in November he shared [this issue](https://github.com/Shopify/polaris/issues/521) with me and shared that there was a decision made as a result of this issue (and potentially another) that prevented the addition of DOM callbacks such as `onKeyPress` (among others) as well as exposing the `ref` for the element.

Something of note is `onKeyPress` is a deprecated event handler. If the team is able to align and green-light adding `onKeyDown` and `onKeyUp` then I would be more than happy to adjust this pull request to include those event handlers on the `TextField` component.

If for some reason the team still finds that adding either of these events is less than preferred, I would appreciate some alternative ideas that are less of a hack.

2023-04-17 14:28 UTC, QuintonC commented on polaris-react/src/components/TextField/TextField.tsx
> +  blurOnEnterKeyPress?: boolean;
[`onKeyPress` is deprecated ](https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event) 😅

2023-04-17 17:17 UTC, chloerice commented
> Ideally, yes, `onKeyPress` would be the preferred way to do this. However, when I spoke with @kyledurand back in November he shared [this issue](https://github.com/Shopify/polaris/issues/521) with me and shared that there was a decision made as a result of this issue (and potentially another) that prevented the addition of DOM callbacks such as `onKeyPress` (among others) as well as exposing the `ref` for the element.

Ah okay, that's a good call. Especially important to consider since we're aligning APIs across Shopify right now. It sounds like wrapping the field in a div to handle the event for special circumstances like yours needs to continue to be the route for this stuff. TextField has an exhorbadent number of props and the API will be changing in the next few months along with all other form input components.

2023-05-01 13:42 UTC, closed without merging