[Toast] Updates to fit a more compact layout
Shopify/polaris-react-archive pull request #7763
Opened 2022-11-18 15:12 UTC by n-filatov

### WHY are these changes introduced?

Resolves: https://github.com/Shopify/polaris/issues/7766

Updates the toast to fit a more compact layout. 

Figma: https://www.figma.com/file/wgbt21f1PZm5lrUecbB5oY/%F0%9F%8D%9E-Toast-component-rework?t=t1DGV6KQXGXBfkaQ-0

### WHAT is this pull request doing?

Redesign screenshots:

<details>
<summary>Default</summary>

Before:
<img width="194" alt="default Toast component before changes" src="https://user-images.githubusercontent.com/11233957/203293475-8ee315bd-94f9-4413-b9da-ada89f74b9fa.png">

After:
<img width="252" alt="default Toast component after changes" src="https://user-images.githubusercontent.com/11233957/203294027-2e37d8a5-146e-468c-bc2e-e13015397545.png">

</details>

<details>
<summary>With Action</summary>

Before:
<img width="304" alt="Toast with action before changes" src="https://user-images.githubusercontent.com/11233957/203293640-f0a2a97a-ef7c-4771-a5ec-f58439452c94.png">

After:
<img width="221" alt="Toast with action after changes" src="https://user-images.githubusercontent.com/11233957/203294132-9e40966a-b991-4008-b767-f829ebea89f7.png">
</details>

<details>
<summary>Error</summary>

Before:
<img width="364" alt="Toast with error before changes" src="https://user-images.githubusercontent.com/11233957/203293759-7a2207ec-5160-477b-8ee6-b03593cc0dd2.png">

After:
<img width="243" alt="Toast with error after changes" src="https://user-images.githubusercontent.com/11233957/203294225-025cd97a-af39-4b7b-a02e-ba4f92c153fe.png">
</details>

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

#### Test in spin

Spin instance: https://admin.web.nf-tost-web.nikita-filatov.eu.spin.dev/store/shop1/products?selectedView=all

<details>
<summary>Default toast</summary>

Create a new product here: [link](https://admin.web.nf-tost-web.nikita-filatov.eu.spin.dev/store/shop1/products/new)

**Expected result**
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/11233957/203316338-b8a97d25-ef8a-4666-8b54-37fdd07ce748.png">
</details>

<details>
<summary>Toast with error</summary>

1. Create a new product here: [link](https://admin.web.nf-tost-web.nikita-filatov.eu.spin.dev/store/shop1/products/new)

2. Before clicking on the Save button disable the wifi:
![image](https://user-images.githubusercontent.com/11233957/203317060-85781e21-69d1-4f78-8902-823dfb1b8edd.png)

**Expected result:**
<img width="976" alt="image" src="https://user-images.githubusercontent.com/11233957/203317249-ce3b54ab-7123-4ec9-ac9c-ad69fdf11658.png">
</details>

#### Test on local machine

1. Open http://localhost:6006/?path=/story/all-components-toast--default
5. Check
2.1 Default toast
2.2. Toast with action
2.3 Toast with error

</details>

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2022-11-22 11:33 UTC, n-filatov commented
/snapit

2022-11-22 16:33 UTC, sarahill approved these changes
This looks great!

2022-11-22 16:48 UTC, kyledurand approved these changes
Looks great to me 👍

2022-11-22 16:48 UTC, kyledurand commented on .changeset/perfect-games-cough.md
> +Redesign the Toast component to a more compact layout
```suggestion
Updated the Toast component to a more compact layout
```

2022-11-22 16:48 UTC, kyledurand commented on polaris-react/src/components/Frame/components/Toast/Toast.scss
> +.LeftIcon {
Can we call this `LeadingIcon` or just `Icon` instead? We're working towards removing left / right / top / bottom phrasing from the system. Not a blocker but if you could make the change here and to `leftIconMarkup` => `leadingIconMarkup` or `iconMarkup` that would be awesome

2022-11-22 17:16 UTC, heyjoethomas commented
Can we double check the tokens being used here? In the Figma doc there are lots of incorrect tokens being used. For example, we shouldn't be using border tokens to style text.

2022-11-22 17:16 UTC, n-filatov commented on polaris-react/src/components/Frame/components/Toast/Toast.scss
> +.LeftIcon {
Got it, thank you for feedback 🙏

Fixed:
https://github.com/Shopify/polaris/blob/173bbf95a89aa93bde219f0c0566f381fc07be72/polaris-react/src/components/Frame/components/Toast/Toast.tsx#L65-L69

2022-11-22 17:18 UTC, n-filatov commented on .changeset/perfect-games-cough.md
> +Redesign the Toast component to a more compact layout
Thanks, fixed!

2022-11-22 17:26 UTC, n-filatov commented
> Can we double check the tokens being used here? In the Figma doc there are lots of incorrect tokens being used. For example, we shouldn't be using border tokens to style text.

Thanks for the very useful comment, Joe! 
@jameswfindlater is now on vacation till the next week. I will meet with him to clarify the tokens which we should use here. Until then, I will mark the PR WIP

2022-11-22 17:29 UTC, heyjoethomas commented
> > Can we double check the tokens being used here? In the Figma doc there are lots of incorrect tokens being used. For example, we shouldn't be using border tokens to style text.
> 
> Thanks for the very useful comment, Joe! @jameswfindlater is now on vacation till the next week. I will meet with him to clarify the tokens which we should use here. Until then, I will mark the PR WIP

Sounds good. If y'all want to jam together on it just reach out. Happy to jump in a session and collab on it.

2022-11-22 17:37 UTC, sarahill commented
Thanks for catching that @heyjoethomas. I noticed that when I was adding them to the UI Kit. Here's a link to the [branch in Figma](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/branch/BQX9uuadoVUFTcCfJ2lY2Z/Polaris-Components?node-id=364%3A1236&t=JjVXM0AtK92Sc5E2-1)

2022-11-23 11:21 UTC, n-filatov commented
> Thanks for catching that @heyjoethomas. I noticed that when I was adding them to the UI Kit. Here's a link to the [branch in Figma](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/branch/BQX9uuadoVUFTcCfJ2lY2Z/Polaris-Components?node-id=364%3A1236&t=JjVXM0AtK92Sc5E2-1)

@sarahill thanks for the Figma link. I have changed the tokens in my PR. The main UI difference is the color for action text, it will be like the main text(using --p-text-on-interactive token)

https://github.com/Shopify/polaris/blob/e8d063dabfa257df3dbe91523c093cbc83c5693e/polaris-react/src/components/Frame/components/Toast/Toast.scss#L25

https://github.com/Shopify/polaris/blob/e8d063dabfa257df3dbe91523c093cbc83c5693e/polaris-react/src/components/Frame/components/Toast/Toast.scss#L51

It will look like this:

<img width="358" alt="Tooltip text on interactive" src="https://user-images.githubusercontent.com/11233957/203533329-95599b43-be61-4f3d-a73d-cd2a72d27fac.png">

2022-11-23 18:14 UTC, sarahill approved these changes
Thanks for updating the tokens. Looks good 👍

2022-11-23 20:49 UTC, LauraAubin approved these changes
Great work! Tophat looks good

<img width="243" alt="Screenshot 2022-11-23 at 3 46 44 PM" src="https://user-images.githubusercontent.com/22782157/203643438-58caceec-94c8-46e8-b150-c19959e267b5.png">

<img width="223" alt="Screenshot 2022-11-23 at 12 20 51 PM" src="https://user-images.githubusercontent.com/22782157/203643461-032516d8-9231-41af-8f75-8a84ee339b30.png">

<img width="280" alt="Screenshot 2022-11-23 at 12 20 28 PM" src="https://user-images.githubusercontent.com/22782157/203643474-f0c2d404-981b-4677-8856-7d1db7cadb5e.png">

2022-11-23 20:50 UTC, LauraAubin commented
I think we should also create an issue to update the action text/close button color when there are available tokens.

2022-11-23 20:59 UTC, sarahill requested changes
Tokens are good but I just noticed 2 things:
- Close button isn't center aligned when there's an action present
- The designs look like they have a shadow but I'm not seeing that here.. correct me if I'm missing it though: `shadow-popover`

close button not center
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/8629173/203644945-273e3281-38ae-4b80-9dd7-13b289c07093.png">

shadow (it's subtle)
<img width="839" alt="image" src="https://user-images.githubusercontent.com/8629173/203645017-ffae9aa5-a2e7-416f-941d-eee8e82d8348.png">

cc: @jameswfindlater

2022-11-28 11:20 UTC, n-filatov commented
> Tokens are good but I just noticed 2 things:
> 
> * Close button isn't center aligned when there's an action present
> * The designs look like they have a shadow but I'm not seeing that here.. correct me if I'm missing it though: `shadow-popover`
> 
> close button not center <img alt="image" width="1164" src="https://user-images.githubusercontent.com/8629173/203644945-273e3281-38ae-4b80-9dd7-13b289c07093.png">
> 
> shadow (it's subtle) <img alt="image" width="839" src="https://user-images.githubusercontent.com/8629173/203645017-ffae9aa5-a2e7-416f-941d-eee8e82d8348.png">
> 
> cc: @jameswfindlater

Yea, my bad. Thanks for noticing 🙌.

1. Added box-shadow:
https://github.com/Shopify/polaris/blob/9cd736016083755a970399e440f7771a79377579/polaris-react/src/components/Frame/components/Toast/Toast.scss#L13

2. Fixed cross icon position:
<img width="288" alt="image" src="https://user-images.githubusercontent.com/11233957/204263464-fa3fd88c-d397-49dc-91ab-0f5a4c997d39.png">

2022-11-28 16:14 UTC, sarahill approved these changes

2022-11-29 16:15 UTC, LauraAubin approved these changes

2022-11-29 22:17 UTC, sarahill commented
Following up on UI Kit updates here: I went ahead and merged in the `Toast` updates to the UI Kit and will publish those changes one this branch is merged :)

2022-12-01 15:53 UTC, jameswfindlater approved these changes
Looking great ... Thank you everyone for doing this!

2022-12-01 17:47 UTC, merged