[Layout Foundation][Box] Add support for passing in role attribute
Shopify/polaris-react-archive pull request #7799
Opened 2022-11-24 16:40 UTC by chazdean

### WHY are these changes introduced?

Supports #7797 which needs access to role attribute 

### WHAT is this pull request doing?

Adds role attribute support to `Box`

2022-11-24 17:25 UTC, chazdean commented
Decided to add role manually as a Type rather then extending `React.HTMLAttributes<HTMLElement>`
- This way we don't open up `Box` to all HTML attributes
- This also allows more control as status, presentation and combobox are they only other roles currently used in web

2022-11-24 17:34 UTC, aveline requested changes, later dismissed
I think you are missing `role` in `createElement` so it actually gets applied to the element?

2022-11-24 17:38 UTC, aveline commented
For context, just wanted to add that we are creating the list of allowable roles manually to intentionally discourage the use of role when there are suitable semantic html elements that should be used instead.

Ex.
❌ `<div role="nav">`
✅ `<nav>`

2022-11-24 20:53 UTC, kyledurand reviewed
Looking good but I think we can be a bit more intentional about what this prop should be used for 👍

2022-11-24 20:53 UTC, kyledurand commented on polaris-react/src/components/Box/Box.tsx
> +  /** role of box */
```suggestion
  /** Aria role */
```

2022-11-24 20:53 UTC, kyledurand commented on polaris-react/src/components/Box/Box.tsx
> +type Role = 'status';
```suggestion
```

2022-11-24 20:53 UTC, kyledurand commented on polaris-react/src/components/Box/Box.tsx
> +  role?: Role;
Let's keep these based the types we know are a11y related

```suggestion
  role?: Extract<React.AriaRole, 'status'>;
```

We'll probably allow all or most of what's avaliable in `AriaRole` but for now we can be strict

2022-11-25 14:23 UTC, chazdean commented on polaris-react/src/components/Box/Box.tsx
> +  role?: Role;
I like this 👌🏾

2022-11-25 14:26 UTC, kyledurand approved these changes
✨

2022-11-25 14:37 UTC, merged