[TextField] Add an icon button and action.
Shopify/polaris-react-archive pull request #7810
Opened 2022-11-30 11:03 UTC by haskelash-shopify

### WHY are these changes introduced?

Part of shopify/retail-upmarket#619

### WHAT is this pull request doing?

Add an optional icon button and action inside the text field.
The icon is a generalized version of the already-implemented clear button.

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React, {useState, useCallback} from 'react';
import {HideMinor, ViewMinor} from '@shopify/polaris-icons';

import {TextField, Page} from '../src';

export function Playground() {
  const [textFieldValue, setTextFieldValue] = useState('Jaded Pixel');
  const [showing, setShowing] = useState(false);

  const handleTextFieldChange = useCallback(
    (value: string) => setTextFieldValue(value),
    [],
  );

  const handleIconButtonClick = useCallback(
    () => setShowing(!showing),
    [showing],
  );

  return (
    <Page title="Playground">
      <TextField
        label="Store name"
        value={showing ? textFieldValue : '••••••'}
        onChange={handleTextFieldChange}
        iconButton={{
          icon: showing ? HideMinor : ViewMinor,
          accessibilityLabel: 'PIN',
        }}
        onIconButtonClick={handleIconButtonClick}
        autoComplete="off"
      />{' '}
    </Page>
  );
}

```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2022-11-30 15:00 UTC, samrose3 submitted a review, later dismissed
Nice work, tested and verified 🎩 💯 thanks for this contribution, @haskelash-shopify

2022-11-30 19:30 UTC, chloerice requested changes
Hey @haskelash-shopify 👋🏽 I'm wary of adding new props to `TextField` since its API and source are already really complex, especially since this functionality is already supported with the `suffix` prop (see example in this [sandbox](https://codesandbox.io/s/textfield-suffix--hide-show-pin-button-3m2h7s?file=/App.js)). But I'm not opposed to adding an explicit prop for an action if it's generic so it can support other use cases.

2022-11-30 19:30 UTC, chloerice commented on polaris-react/src/components/TextField/TextField.tsx
> +  } | null;
Let's use the `action` prop pattern to enable configuration in the same way as other component actions, like `Card.actions`

```suggestion
  /** An action rendered at the end of the input  */
 action?: ComplexAction | React.ReactNode;
```

2022-11-30 19:30 UTC, chloerice commented on polaris-react/src/components/TextField/TextField.tsx
> +  onIconButtonClick?(id: string): void;
(Not needed with the `action` prop interface)

```suggestion
```

2022-11-30 19:30 UTC, chloerice commented on polaris-react/src/components/TextField/TextField.tsx
> +  ) : null;
```suggestion
let actionMarkup = null;

if (action) {
 actionMarkup = React.isValidElement(action) ? action : buttonFrom(action);
}
```

2022-11-30 19:30 UTC, chloerice commented on polaris-react/src/components/TextField/TextField.tsx
> +  iconButton,
```suggestion
  action
```

2022-11-30 19:30 UTC, chloerice commented on polaris-react/src/components/TextField/TextField.tsx
> +  onIconButtonClick,
```suggestion
```

2022-11-30 19:30 UTC, chloerice commented on polaris-react/src/components/TextField/TextField.tsx
> +
```suggestion
```

2022-11-30 19:30 UTC, chloerice commented on polaris.shopify.com/content/components/text-field.md
> +    description: Use to allow merchants to add an icon button inside a text field.
```suggestion
  - fileName: text-field-with-action.tsx
    title: With action
    description: Use to present merchants with an action to take within the text field, like hiding or showing sensitive input.
```

2022-11-30 19:30 UTC, chloerice commented on polaris.shopify.com/pages/examples/text-field-with-icon-button.tsx
> +  const handleIconButtonClick = useCallback(
```suggestion
  const handleActionClick = useCallback(
```

2022-11-30 19:30 UTC, chloerice commented on polaris.shopify.com/pages/examples/text-field-with-icon-button.tsx
> +      value={showing ? textFieldValue : '••••••'}
```suggestion
      value={textFieldValue}
      inputMode="numeric"
      type={showing ? "text" : "password"}
      minLength={6}
      maxLength={6}
```

2022-11-30 19:30 UTC, chloerice commented on polaris.shopify.com/pages/examples/text-field-with-icon-button.tsx
> +      onIconButtonClick={handleIconButtonClick}
```suggestion
      action={{
        onClick: handleActionClick,
        icon: showing ? HideMinor : ViewMinor,
        accessibilityLabel: showing ? "Hide PIN" : "Show PIN",
      }}
```

2022-11-30 19:30 UTC, chloerice commented on polaris-react/src/components/TextField/TextField.tsx
> +          {iconButtonMarkup}
```suggestion
          {actionMarkup}
```

2022-11-30 19:30 UTC, chloerice commented on polaris.shopify.com/src/data/props.json
> +          "description": "Show an icon button within the input",
```suggestion
          "name": "action",
          "value": "ComplexAction",
          "description": "An action rendered at the end of the input",
```

2022-11-30 19:30 UTC, chloerice commented on polaris.shopify.com/src/data/props.json
> +        },
```suggestion
```

2022-11-30 19:30 UTC, chloerice commented on polaris-react/src/components/TextField/TextField.scss
> +.IconButton {
```suggestion
.ClearButton {
```

2022-12-01 21:23 UTC, alex-page commented on polaris-react/src/components/TextField/TextField.tsx
> +  } | null;
I think this is an example where we should be adding composition instead of new properties. Is there a way this can be built where we allow `React.ReactNode` and it's seen as a prefix or suffix?

2022-12-01 22:21 UTC, samrose3 commented on polaris-react/src/components/TextField/TextField.tsx
> +  } | null;
I agree with Alex here. That would make this more flexible. Would you imagine the usage be something like the following?

```tsx
<TextField suffix={iocnButtonMarkup} />
```

2022-12-02 00:08 UTC, chloerice commented on polaris-react/src/components/TextField/TextField.tsx
> +  } | null;
Yep, exactly 💯 Checkout the sandbox demo mentioned [here](https://github.com/Shopify/polaris/pull/7810#pullrequestreview-1199748193)

2022-12-03 21:23 UTC, haskelash-shopify commented
/shipit

2022-12-08 16:44 UTC, goyox86 reviewed
Not much experience on this one @haskelash-shopify will defer to the other Retail Upmarket members/Polaris owners to review this one.

2023-02-02 09:07 UTC, CalvinWalzel commented
@haskelash-shopify is this still relevant?

2023-02-02 09:28 UTC, haskelash-shopify commented
> @haskelash-shopify is this still relevant?

@CalvinWalzel, nope. Closing it now.

2023-02-02 09:28 UTC, closed without merging