[Layout Foundations] Rebuild `DropZone` with layout primitives
Shopify/polaris-react-archive pull request #7905
Opened 2022-12-13 15:12 UTC by chazdean

### WHY are these changes introduced?

Fixes #7840 

### WHAT is this pull request doing?

Refactors `DropZone` and its child components to use our layout primitives.

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2023-01-10 19:56 UTC, yurm04 commented on polaris-react/src/components/Box/Box.tsx
> +  onClick?: React.MouseEventHandler<HTMLElement>;
i've been out for a bit so take this comment with a grain of salt: adding the drag (and maybe even onClick?) is a departure from our `Box` as a presentational component principle. Are there other approaches we can take that don't add these props, or are we cool with expanding the purpose of `Box` to include more use cases?

2023-01-10 21:02 UTC, chazdean commented on polaris-react/src/components/Box/Box.tsx
> +  onClick?: React.MouseEventHandler<HTMLElement>;
I don't think this has come up yet, looking forward to hearing some of the feedback around this as I was also unsure of the best approach in regards to handling the drag and onClick functionality

2023-01-17 16:20 UTC, aveline commented on polaris-react/src/components/Box/Box.tsx
> +  onClick?: React.MouseEventHandler<HTMLElement>;
Let's avoid adding the `drag` and `onClick` to `Box` at this time. We should keep our focus for this project on layout and presentational components. Any elements that need interactive support are not presentational and so fall outside the scope of layout.

In a way this forces us to be aware of separation of concerns between layout and interactive elements.

2023-01-17 16:51 UTC, aveline requested changes
Nice to see `AlphaStack` replace all those instances of `Stack` 🎉

2023-01-17 16:51 UTC, aveline commented on polaris-react/src/components/DropZone/DropZone.tsx
> +        <Box
What you could try here is separating the visual styles from the interactive functionality by having both the `Box` for the visual and layout styles and having the `div` for the interactive functionality.

2023-01-19 16:25 UTC, chazdean commented on polaris-react/src/components/Box/Box.tsx
> +  onClick?: React.MouseEventHandler<HTMLElement>;
That makes sense 👍🏾

2023-01-19 17:06 UTC, nayeobkim approved these changes
Reviewed Chromatic and Storybook—all visually looked good to me

2023-01-31 17:28 UTC, aveline commented on polaris-react/src/components/DropZone/DropZone.tsx
> +                <div className={styles.overlayContainer}>{text}</div>
Can `.overlayContainer` be removed?

2023-01-31 18:17 UTC, chazdean commented on polaris-react/src/components/DropZone/DropZone.tsx
> +                <div className={styles.overlayContainer}>{text}</div>
Yes! Forget to take that out

2023-02-01 17:06 UTC, laurkim approved these changes

2023-02-01 17:23 UTC, aveline approved these changes

2023-02-01 17:46 UTC, merged