[Tooltip] Add support for a hover delay before tooltip is displayed
Shopify/polaris-react-archive pull request #7910
Opened 2022-12-13 20:15 UTC by henryyi

### WHY are these changes introduced?

Resolves: Shopify/core-workflows/issues/609

Items in the side-nav bar may have a tooltip if the label is truncated. As user may be mousing down the navigation it would not be user friendly if the tooltip pops up while moving down the nav.

![tooltip-hover-delay](https://user-images.githubusercontent.com/1307190/207434028-be95386d-0fed-4aa5-aae5-aad9c8d99a2a.gif)

### WHAT is this pull request doing?

A `hoverDelay` prop is added to the `ToolTip` component which allow consumers to specify the required delay in milliseconds. By default there is no delay.

### How to 🎩

An example can be seen in [storybook](https://polaris.ttd.jita-yi.us.spin.dev/?path=/story/all-components-tooltip--with-hover-delay).

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2022-12-13 20:15 UTC, henryyi commented
/snapit

2022-12-13 20:39 UTC, jeradg approved these changes
Code and 🎩 LGTM!

2022-12-13 20:57 UTC, kushp approved these changes
🎩 already done, code LGTM

2022-12-13 20:57 UTC, kushp commented on polaris-react/src/components/Tooltip/Tooltip.stories.tsx
> +        <Tooltip content="This shoud appear right away.">
nit: should*

2022-12-14 12:58 UTC, gui-santos requested changes
It looks great!

I got only one question before my approval :)

2022-12-14 12:58 UTC, gui-santos commented on polaris-react/src/components/Tooltip/Tooltip.tsx
> +      clearTimeout(hoverDelayTimeout.current);
I think my only question about the code is if we need to clearTimeout also when the component unmounts, do we?

If I got it right, we are only clearing it in the MouseLeave event

2022-12-14 13:27 UTC, henryyi commented on polaris-react/src/components/Tooltip/Tooltip.tsx
> +      clearTimeout(hoverDelayTimeout.current);
That's a good point I'll make sure to clear it.

2022-12-14 13:32 UTC, henryyi commented on polaris-react/src/components/Tooltip/Tooltip.tsx
> +      clearTimeout(hoverDelayTimeout.current);
I've made the change.

2022-12-14 14:42 UTC, gui-santos approved these changes
Looks great! 🍰

2022-12-14 14:44 UTC, nabihaalikhan approved these changes
looks great 🚢

2022-12-14 15:30 UTC, merged