Deprecate breadcrumbs and allow singular breadcrumb prop on Page and Breadcrumbs
Shopify/polaris-react-archive pull request #8135
Opened 2023-01-23 19:01 UTC by itwasmattgregg

### WHY are these changes introduced?

Fixes #0000 

### WHAT is this pull request doing?

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2023-01-23 19:57 UTC, alex-page commented on polaris-react/src/components/Breadcrumbs/Breadcrumbs.tsx
> +  breadcrumb?: CallbackAction | LinkAction;
This will become required in v11?

2023-01-23 19:58 UTC, itwasmattgregg commented on polaris-react/src/components/Breadcrumbs/Breadcrumbs.tsx
> +  breadcrumb?: CallbackAction | LinkAction;
yes

2023-01-23 20:27 UTC, sam-b-rose reviewed
Nice update! Only had a few suggestions

2023-01-23 20:27 UTC, samrose3 commented on polaris-react/src/components/Page/components/Header/Header.tsx
> +    // eslint-disable-next-line no-console
This should be wrapped in its own `if` statement when `breadcrumbs` is used:

```ts
if (breadcrumbs && process.env.NODE_ENV === 'development') {
  console.warn('...')
}
```

2023-01-23 20:27 UTC, sam-b-rose commented on polaris-react/src/components/Breadcrumbs/Breadcrumbs.tsx
> +  breadcrumb?: CallbackAction | LinkAction;
Perhaps we should log a warning that the `breadcrumb` prop should "require" a value if no value is provided to either? A bit clunky but at least a temporary way to notify the developer until the next major update.

2023-01-23 20:27 UTC, sam-b-rose commented on polaris-react/src/components/Page/components/Header/Header.tsx
> +  const breadcrumbMarkup = () => {
Feels a bit odd to have this as a function since it relies on outside scope variables. I think we could keep `breadcrumbMarkup` a variable for simplicity:

```ts
let breadcrumbMarkup = null;
if (breadcrumb) {
  breadcrumbMarkup = // value
} else if (Array.isArray(...) ... ) {
  breadcrumbMarkup = // other value
}
```

2023-01-24 19:03 UTC, itwasmattgregg commented on polaris-react/src/components/Page/components/Header/Header.tsx
> +  const breadcrumbMarkup = () => {
Ah yea I just tend avoid mutable code these days lol I forget it's even possible

2023-02-19 22:13 UTC, alex-page commented on polaris-react/src/components/Breadcrumbs/Breadcrumbs.tsx
> +  breadcrumb?: CallbackAction | LinkAction;
@itwasmattgregg before this ships can we change the name of `breadcrumb` to `backAction`. I am trying to align across the extensions team. See here:
https://github.com/Shopify/app-kit/discussions/150#discussioncomment-4994861

2023-02-19 22:13 UTC, alex-page requested changes
@itwasmattgregg before this ships can we change the name of `breadcrumb` to `backAction`. I am trying to align across the extensions team. See here:
https://github.com/Shopify/app-kit/discussions/150#discussioncomment-4994861

2023-02-22 17:20 UTC, itwasmattgregg commented on polaris-react/src/components/Page/components/Header/Header.tsx
> +    // eslint-disable-next-line no-console
Totally. Have no idea what I was thinking. Good catch

2023-02-22 17:41 UTC, itwasmattgregg commented on polaris-react/src/components/Breadcrumbs/Breadcrumbs.tsx
> +  breadcrumb?: CallbackAction | LinkAction;
Added a warning

2023-02-22 21:11 UTC, alex-page approved these changes

2023-02-23 00:39 UTC, chloerice approved these changes

2023-02-23 00:39 UTC, chloerice commented on .changeset/metal-cows-poke.md
> +Adds new backAction prop and deprecates breadcrumbs in favor of the new singular prop.
```suggestion
Deprecated the `Page` `breadcrumbs` prop in favor of the new `backAction` prop.
```

2023-02-23 01:42 UTC, merged