[SettingToggle] UX improvements
Shopify/polaris-react-archive pull request #8547
Opened 2023-03-03 14:21 UTC by oluwatimio

### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris/issues/8328

[Figma](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/branch/880uUKf3RpIwVO5Xdztqou/Polaris-Components?node-id=2098%3A51&t=nGhmG9Aq5WIo9Iq9-0)
Co-author - @chloerice 

### WHAT is this pull request doing?

|| Small screen | Large screen |
|---|--------|--------|
|[With child content only](https://5d559397bae39100201eedc1-kbrigabmwk.chromatic.com/?path=/story/all-components-settingtoggle--with-only-child-content)|<img width="375" alt="Screenshot 2023-03-08 at 3 52 18 PM" src="https://user-images.githubusercontent.com/18447883/223847561-de9ca977-f231-4ac4-99ab-bc2cfa27d1b6.png">| <img width="756" alt="Screenshot 2023-03-08 at 3 53 31 PM" src="https://user-images.githubusercontent.com/18447883/223847692-485982d2-6d7d-43a1-b80c-9991f024bde4.png">|
|[With title and description](https://5d559397bae39100201eedc1-kbrigabmwk.chromatic.com/?path=/story/all-components-settingtoggle--with-title-and-description)| <img width="367" alt="Screenshot 2023-03-08 at 3 52 57 PM" src="https://user-images.githubusercontent.com/18447883/223847742-0260b30e-fa3a-4625-8453-b1d92a328dff.png"> |<img width="753" alt="Screenshot 2023-03-08 at 3 53 21 PM" src="https://user-images.githubusercontent.com/18447883/223848360-7d18c19f-b14f-47cd-beb3-46199c1f6af2.png">|
|[With all its elements](https://5d559397bae39100201eedc1-kbrigabmwk.chromatic.com/?path=/story/all-components-settingtoggle--with-all-of-its-elements)|<img width="376" alt="Screenshot 2023-03-08 at 3 53 58 PM" src="https://user-images.githubusercontent.com/18447883/223848455-fb7e9ed2-c0ba-4cd8-a229-32c239fbae6b.png">|<img width="754" alt="Screenshot 2023-03-08 at 3 54 11 PM" src="https://user-images.githubusercontent.com/18447883/223848493-ee08e8c9-6969-4ca1-8314-f919dccd51ad.png">| 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

Play with the examples in [the Storybook deploy for this PR](https://5d559397bae39100201eedc1-kbrigabmwk.chromatic.com/?path=/story/all-components-settingtoggle--with-only-child-content), or run Storybook locally:
1. `git checkout settings-toggle-improved`
2. `yarn dev`
3. Your terminal will automatically open a new window or tab and navigate to http://localhost:6006/?path=/story/all-components-settingtoggle--with-only-child-content
4. You can play with the stories or edit their prop combinations in `SettingToggle.stories.tsx`

Tophat the style guide locally:
1. `yarn build && yarn turbo run dev --filter=polaris.shopify.com`
2. Your terminal will automatically open a new window or tab and navigate to https://localhost:3000/components/selection-and-input/setting-toggle

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2023-03-06 18:52 UTC, oluwatimio commented on polaris.shopify.com/content/components/actions/setting-toggle.md
> -    description: Use on settings pages to allow merchants to toggle a setting that has an activated or a deactivated state.
Documentation update from https://github.com/Shopify/polaris/pull/8497

2023-03-06 18:53 UTC, oluwatimio commented on polaris.shopify.com/content/content/accessible-and-inclusive-language.md
> -- Turned on, turned off
Documentation update initially from https://github.com/Shopify/polaris/pull/8497

2023-03-06 18:57 UTC, oluwatimio commented on polaris.shopify.com/content/components/actions/setting-toggle.md
> -    description: Use on settings pages to allow merchants to toggle a setting that has an activated or a deactivated state.
@deannatron @heydouble-a documentation here

2023-03-06 18:57 UTC, oluwatimio commented on polaris.shopify.com/content/content/accessible-and-inclusive-language.md
> -- Turned on, turned off
@heydouble-a @deannatron

2023-03-06 21:46 UTC, chloerice commented
/snapit

2023-03-06 22:17 UTC, jjgali requested changes, later dismissed
When I view polaris.shopify.com on that branch, the example on the website is different than what I'm seeing in storybook, fyi. 
<img width="855" alt="Screenshot 2023-03-06 at 4 17 01 PM" src="https://user-images.githubusercontent.com/77791660/223252652-7c6a9f1c-2547-4784-bfe9-ad5668ff9976.png">

2023-03-06 22:17 UTC, jjgali commented on polaris-react/src/components/SettingToggle/SettingToggle.stories.tsx
> +        <Banner status="info">An Example Banner Child</Banner>
Could we replace this with more realistic copy to match the rest of our component examples? @deannatron are you interested in writing this?

2023-03-07 15:56 UTC, heydouble-a approved these changes

2023-03-07 19:55 UTC, oluwatimio commented
> When I view polaris.shopify.com on that branch, the example on the website is different than what I'm seeing in storybook, fyi. <img alt="Screenshot 2023-03-06 at 4 17 01 PM" width="855" src="https://user-images.githubusercontent.com/77791660/223252652-7c6a9f1c-2547-4784-bfe9-ad5668ff9976.png">

@jjgali Oh this is because the polaris.shopify.com section uses the polaris package that is released and not the one in this PR. I have pushed a temporary update the polaris.shopify.com for this pr to use the snapshot @chloerice created so if you pull this change and run

`yarn && yarn build` you should start seeing it 

<img width="909" alt="Screenshot 2023-03-07 at 2 50 34 PM" src="https://user-images.githubusercontent.com/13557893/223537853-79722b88-058e-475e-bd11-ae9598257078.png">

2023-03-08 22:44 UTC, chloerice approved these changes

2023-03-09 13:26 UTC, oluwatimio commented
/snapit

2023-03-09 14:12 UTC, jjgali approved these changes

2023-03-12 21:53 UTC, alex-page commented on polaris-react/src/components/SettingToggle/SettingToggle.tsx
> +  title?: string;
Hey @oluwatimio. I am not aligned with these changes. You are adding a lot of props and translations to the component. Polaris should focus on creating small composable patterns. Additional props is more maintenance, design opinions, documentation and examples.

I think this component would be better outside of Polaris. We have recently been figuring out patterns and I think this is a good example of what a pattern could be.

2023-03-12 21:54 UTC, alex-page submitted a review, later dismissed
Hey @oluwatimio. I am not aligned with these changes. You are adding a lot of props and translations to the component. Polaris should focus on creating small composable patterns. Additional props is more maintenance, design opinions, documentation and examples.

I think this component would be better outside of Polaris. We have recently been figuring out patterns and I think this is a good example of what a pattern could be cc @sophschneider and @johanstromqvist.

2023-03-13 13:24 UTC, oluwatimio commented
> Hey @oluwatimio. I am not aligned with these changes. You are adding a lot of props and translations to the component. Polaris should focus on creating small composable patterns. Additional props is more maintenance, design opinions, documentation and examples.
> 
> I think this component would be better outside of Polaris. We have recently been figuring out patterns and I think this is a good example of what a pattern could be cc @sophschneider and @johanstromqvist.

Hey @alex-page, so for the translations we added that because of the Off, On and Turn off, Turn on texts. We can possibly allow consumers of the component pass this in the texts they want for these as a prop. That being said, if adding this as a pattern is still preferable/a must, how do we go about that? Would it be just a matter of adding some documentation to the current SettingsToggle docs

2023-03-13 22:47 UTC, alex-page commented
@oluwatimio Totally understand the want to ship these translations as they provide the best design outcome. The challenge is we lose flexibility. If a future need is to ship a "true/false" switch then the component will not suit that need and will need revisions, breaking changes or to be forked.

2023-03-14 21:33 UTC, alex-page commented
If we believe the React prop should be there as it makes a better design we should ship a breaking change and make the property required. Quick recommendations:
- `title` is required breaking change
- `description` is removed and we use `children` instead. I don’t see a lot of value in both of these props. We should have one or the other. Happy to ship the breaking change removing `children` and making `description` required.

I don’t mind the translations shipping. Our team will need to go over components with translations and see if they are required or can be removed.

As I said before in DM’s with some folks. If we don’t see an uptick in this components usage over the next six months we will still look into removing it. Removing it doesn’t mean the guidance or documentation doesn’t exist. It means that we do not maintain a react component for this UI.

2023-03-17 21:30 UTC, chloerice commented on polaris-react/src/components/SettingToggle/SettingToggle.stories.tsx
> +  const toggleId = 'setting-toggle-uuid';
```suggestion
```

2023-03-19 20:34 UTC, alex-page commented
Hey folks, happy with the direction. Not going to block this PR anymore. Feel free to ship if the other Polaris folks are happy. Thanks again @oluwatimio

2023-03-22 21:17 UTC, oluwatimio commented on polaris.shopify.com/content/components/selection-and-input/setting-toggle.md
> +- Include a title
@deannatron @heydouble-a. Chloe and I made the documentation changes requested here. Here's what it looks like

![Screenshot 2023-03-22 at 5 15 40 PM](https://user-images.githubusercontent.com/13557893/227040447-b1961cc8-fcb1-428d-a6d4-401b4760b1bf.png)


If we are okay with this, we can ship the changes :)

2023-03-23 15:29 UTC, oluwatimio commented
Will be merging this as soon as the CI passes!

2023-03-23 16:46 UTC, merged