Add `explore images` icon
Shopify/polaris-react-archive pull request #8861
Opened 2023-04-05 14:54 UTC by AlejandroE

### WHY are these changes introduced?

Adds a new icon to represent the menu action opening free (burst) images in OSE

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2023-04-05 14:55 UTC, AlejandroE commented
CC @osamaghazal01

2023-04-05 15:16 UTC, osamaghazal01 commented
Solves this issue
https://github.com/Shopify/polaris/issues/8862

2023-04-05 15:27 UTC, martenbjork requested changes
Looks great!

The icon description in the `yml` shouldn't be a Markdown table. It should just be a simple string. (I saw that `AddImageMajor` icon had a commented out Markdown table, but that's incorrect — sorry about the confusion!)

2023-04-05 15:30 UTC, martenbjork approved these changes

2023-04-05 15:34 UTC, heyjoethomas commented
Please make sure to add this into the Figma UIKit as well. If you need help or have questions on how to do that feel free to reach out.

2023-04-05 15:36 UTC, AlejandroE commented
@heyjoethomas thanks for the heads up! I'm approaching the end of my day but will figure that out tomorrow :D

2023-04-05 15:38 UTC, osamaghazal01 commented
@heyjoethomas I have access to [this kit](https://www.figma.com/file/mMHFt3kEDNjLMZWowi6gnt/Polaris-Icons?node-id=6%3A10&t=iPLxoBIoVKGvvo8B-1) but I don't have access to edit.

2023-04-05 15:39 UTC, heyjoethomas commented
> @heyjoethomas I have access to [this kit](https://www.figma.com/file/mMHFt3kEDNjLMZWowi6gnt/Polaris-Icons?node-id=6%3A10&t=iPLxoBIoVKGvvo8B-1) but I don't have access to edit.

You can create a branch to add the icon. Then just request a review when ready and I can merge and publish.

2023-04-05 16:14 UTC, kyledurand requested changes
Just make sure to change from major to minor release

2023-04-05 16:14 UTC, kyledurand commented on .changeset/poor-walls-care.md
> +Adds a new icon used to represent exploring a variety of imagery assets
```suggestion
Added ExploreImagesMajor icon
```

2023-04-05 16:14 UTC, kyledurand commented on .changeset/poor-walls-care.md
> +'@shopify/polaris-icons': major
```suggestion
'@shopify/polaris-icons': minor
```

2023-04-06 16:58 UTC, AlejandroE commented
@kyledurand thanks Kyle! made the changes but the checks seem to be flaky, might be github.

2023-04-06 17:12 UTC, kyledurand approved these changes
Code looks good and I pushed up some changes removing extraneous attributes that were causing tests to fail. There may be a chance we'll need to skip the comment check if that still fails. Seems like a false positive. 

Last thing I'm seeing is that the icon isn't centered in its canvas. I'm assuming that's intentional but wanted to flag it just in case

![image](https://screenshot.click/06-10-kth4h-k8a15.png)

2023-04-10 16:16 UTC, osamaghazal01 commented
Thank you folks :)

2023-04-12 15:04 UTC, merged