[Page, Layout] Update styles
Shopify/polaris-react-archive pull request #9317
Opened 2023-05-29 19:48 UTC by kyledurand

Closes: https://github.com/Shopify/polaris-summer-editions/issues/25

**NOTES:** 
- Primary action and pagination will be updated once button updates are in
- Destructive secondary action styles may change once they hit figma

https://github.com/Shopify/polaris/assets/6844391/4d355915-a808-4b6a-9dfa-62773a122f2d

2023-05-30 19:18 UTC, sophschneider reviewed
Left some questions!

2023-05-30 19:18 UTC, sophschneider commented on polaris-react/src/components/ActionMenu/components/RollupActions/RollupActions.scss
> +        @include focus-ring($style: 'focused');
should we just use `outline` instead of the `focus-ring` mixin here since we want to deprecate it eventually? then you wouldn't have to change the `_focus-ring.scss` file. I think I might do the same in `Banner`. 

there's [instructions here](https://github.com/Shopify/polaris/issues/7595#issuecomment-1314580432).

I also did it with [banner here](https://github.com/Shopify/polaris/pull/8780/files) but I reverted it due to a stale branch then forgot to remerge.

Once you add the custom focus ring you can add it to [this list](https://github.com/Shopify/polaris/issues/7595#issuecomment-1488980764)

it should be something like
```
outline: var(--p-border-width-2) solid var(--p-focused);
outline-offset: var(whatever-wideness-space-token);
```

2023-05-30 19:18 UTC, sophschneider commented on polaris-react/src/components/ActionMenu/components/RollupActions/RollupActions.tsx
>  export function RollupActions({
revert spacing?

2023-05-30 19:18 UTC, sophschneider commented on polaris-react/src/styles/foundation/_focus-ring.scss
> +  }
same as above, I think I would rather use outlines then extend this mixin! what do you think @alex-page ?

2023-05-30 19:18 UTC, sophschneider commented on polaris-react/src/components/ActionMenu/components/Actions/Actions.tsx
> +    <ButtonGroup spacing="tight">
should we put this behind the feature flag?

2023-05-30 19:18 UTC, sophschneider commented on polaris-react/src/components/ActionMenu/components/SecondaryAction/SecondaryAction.tsx
> +    >
is this change needed?

2023-05-30 19:18 UTC, sophschneider commented on polaris-react/src/components/HorizontalStack/HorizontalStack.tsx
> +type Element = 'div' | 'span' | 'ul' | 'li';
what's this for?

2023-05-30 19:24 UTC, kyledurand commented on polaris-react/src/styles/foundation/_focus-ring.scss
> +  }
Yeah I'm down with that approach! 🙇

2023-05-30 19:25 UTC, kyledurand commented on polaris-react/src/components/HorizontalStack/HorizontalStack.tsx
> +type Element = 'div' | 'span' | 'ul' | 'li';
At one point I was trying to cleanup secondary actions by using UnstyledButton, which would have needed HorizontalStack as a child and div isn't valid html inside a button so I added the ability to use span / ul / li. I can revert this change

2023-05-30 19:43 UTC, kyledurand commented on polaris-react/src/styles/foundation/_focus-ring.scss
> +  }
I just remembered there was an issue with outline not respecting border radius in Safari. It's mentioned in the link above:

> We also noticed that Safari did not support border-radius with outline, though this has been resolved in the latest[ preview release of Safari](https://webkit.org/blog/13575/release-notes-for-safari-technology-preview-157/).

We need to support the two latest versions of Safari so I'm not sure we should make the switch just yet. Should be an easy migration when we can though.

2023-05-30 20:09 UTC, kyledurand commented on polaris-react/src/styles/foundation/_focus-ring.scss
> +  }
More context: the rounded outline patch was released in 16.4, Safari is now up to 16.5. It's likely merchants won't see us trying to round outlines before 16.6 so we might be ok to ship outlines as a replacement but it's cutting it close. It's also not breaking the experience if a merchant sees a boxy outline...Let's see what Alex says.

2023-05-30 20:14 UTC, qt314 approved these changes
🙌✨

2023-05-30 23:22 UTC, sarahill requested changes
1. Misalignment of title and badge
It looks like this is due to 2px margin added to the title. Can we remove that and add `padding-top: 2px` and `padding-bottom: 2px` to the `TitleMetadataWrapper`? This will fix the alignment and keep the height at `28px` to match the buttons.

2. Space between title and subtitle
Add a `2px` gap between the `TitleMetadataWrapper` and subtitle. With the adding padding to the `TitleMetadataWrapper` that'll be a total of `4px`

3. Space between back button icon and title
Decrease space from `8px` to `4px`

4. Title font-weight
Title font weight should be `bold` `700`. I'm not sure to what extent these will be updated once the `Text` component is updated though.

5. Subtitle font-size
Subtitle uses `bodySm` or `12px` size and `16px` line-height

6. Top and bottom padding between top bar and content
Increase spacing from `20px` to `24px`. Keep small screen as is.

7. Alignment issues
Looks like there are some more alignment issues between title, icons, buttons, etc depending on if some content is visible or not. I don't think adding the padding will fully resolve these. Just flagging for now.
<img width="1165" alt="image" src="https://github.com/Shopify/polaris/assets/8629173/4bba1339-2ebf-460f-8d2c-5be493064917">

8. With destructive secondary action
Let's update this to use the plain destructive style
<img width="600" alt="image" src="https://github.com/Shopify/polaris/assets/8629173/0abc4ea3-6baa-4fbe-aed5-0c3e84285515">

2023-05-31 04:46 UTC, alex-page commented on polaris-react/src/styles/foundation/_focus-ring.scss
> +  }
We can start using outline now, worst case scenario old safari is square but that is not a huge deal. Thanks for looping me in.

2023-05-31 04:47 UTC, alex-page commented on polaris-react/src/styles/foundation/_focus-ring.scss
> +  }
We could even ship a quick "non" uplift change to update to focus ring to use outline everywhere if it helps.

2023-05-31 12:17 UTC, kyledurand commented on polaris-react/src/styles/foundation/_focus-ring.scss
> +  }
I'll take a look at refactoring _focus_ring this am

2023-05-31 15:51 UTC, kyledurand commented on polaris-react/src/styles/foundation/_focus-ring.scss
> +  }
https://github.com/Shopify/polaris/pull/9327

2023-06-01 13:05 UTC, kyledurand commented
@sarahill I've made a bunch of those changes but a lot of the misalignment was due to the buttons still being oversized

With buttons:
![image](https://screenshot.click/01-45-piioy-i2oeo.png)

Without buttons
![image](https://screenshot.click/01-45-piioy-i2oeo.png)

I've also added new icon color tokens and used one for destructive secondary action

2023-06-01 18:26 UTC, sarahill approved these changes

2023-06-01 18:35 UTC, merged