[Select] updates
Shopify/polaris-react-archive pull request #9369
Opened 2023-06-02 22:18 UTC by qt314

### WHY are these changes introduced?

Fixes #0000 

### WHAT is this pull request doing?

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2023-06-05 21:25 UTC, sarahill requested changes
Disabled state still has interactions
![2023-06-05 14 24 20](https://github.com/Shopify/polaris/assets/8629173/42c33011-bbe3-4dea-8558-18ea949b7f68)

2023-06-05 22:10 UTC, qt314 commented
@sarahill should be fixed! Thanks for catching

2023-06-05 23:37 UTC, sarahill approved these changes

2023-06-06 15:37 UTC, mateus approved these changes

2023-06-06 17:33 UTC, merged