Remove deprecated LegacyCard in LegacyFilters stories
Shopify/polaris-react-archive pull request #9393
Opened 2023-06-07 04:32 UTC by jesstelford

2023-06-07 05:22 UTC, jesstelford commented on polaris-react/src/components/Tag/Tag.scss
> +      padding-inline-end: 0;
Sneaky fix here; The `se23` `padding-inline` above accidentally overwrote the `.removable` style. Due to specificity, we have to duplicate it here so it's applied correctly.

2023-06-07 05:25 UTC, jesstelford commented on polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/ConnectedFilterControl.scss
> +  flex-shrink: 0;
Only happens when the `children` prop is passed to `LegacyFilters`:

![overlap](https://github.com/Shopify/polaris/assets/612020/e089ac91-4427-45e1-821d-6de421a0eee0)

Disallowing shrinking fixes it:

![no-overlap](https://github.com/Shopify/polaris/assets/612020/25e1fc13-ce68-41f4-982c-6a986097c244)

2023-06-07 05:26 UTC, jesstelford commented on polaris-react/src/components/LegacyFilters/LegacyFilters.stories.tsx
> +      <Card padding="0">
'tis legacy, so... bu-bye.

But also, it was causing some rendering artefacts that aren't present with the new `Card`. These are just stories, so very little risk here.

2023-06-08 17:56 UTC, sarahill reviewed
1. Padding should be `12px` all around
<img width="1102" alt="image" src="https://github.com/Shopify/polaris/assets/8629173/8e75394c-5ba6-474e-9db3-d1e0af484581">

2. Update buttons to use the `large` size so they match the height of the input -> we JUST added these
<img width="365" alt="image" src="https://github.com/Shopify/polaris/assets/8629173/ba55f04b-4298-4a3f-8486-5d8b302e17f3">

2023-06-08 17:57 UTC, sarahill requested changes
See [comment](https://github.com/Shopify/polaris/pull/9393#pullrequestreview-1470502704) for details

2023-06-09 02:52 UTC, jesstelford commented
> Padding should be 12px all around

😩 This spacing has changed in the design since I opened this PR.

I'm going to close this and combine it with https://github.com/Shopify/polaris/pull/9394 into https://github.com/Shopify/polaris/pull/9376 since they're all intricately linked together (and all their designs changed since I started work on it).

2023-06-09 02:52 UTC, closed without merging