Update `Button` font size for small screens
Shopify/polaris-react-archive pull request #9437
Opened 2023-06-09 21:29 UTC by aveline

### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-summer-editions/issues/84

### WHAT is this pull request doing?

- Adjusts text size on buttons for small screens
- Bump up large button text size on small screens

### How to 🎩

View in Storybook

2023-06-12 16:43 UTC, aaronccasanova approved these changes

2023-06-12 17:01 UTC, sarahill requested changes
Default button size should be `32px`, I'm seeing `28px`. Padding is bumped to `6px` top/bottom – [Figma](https://www.figma.com/file/jLLkmo9r28hiqPvf4s90E4/Polaris-Uplift-Components-%5Bgen3%E2%80%93alpha%5D?type=design&node-id=85623-51127&t=SXEbLBIVvN4ksNqJ-4)

2023-06-12 18:44 UTC, aveline commented
I thought that vertical padding change was already in, but I guess [it got reverted](https://github.com/Shopify/polaris/pull/9411). Added it back in.

2023-06-13 18:57 UTC, sarahill approved these changes

2023-06-13 20:13 UTC, merged