[LegacyCard.Section] Remove extra padding when flush is true
Shopify/polaris-react-archive pull request #9597
Opened 2023-07-04 09:12 UTC by jhalvorson

Resolves Shopify/polaris-summer-editions#376, Shopify/polaris-summer-editions#727

When the `$se23` variable is set to true a more specific CSS selector causes the `LegacyCard.Section` component to have unnecessary padding. Since this is a flush component its padding should be `0`.

|                           | Before | After |
|----------------|--------|------|
| **With $se23**       | ![Screenshot 2023-07-04 at 10 06 36](https://github.com/Shopify/polaris/assets/10282220/04e5ae2b-3b84-469f-b50d-2ef9d1bc7645) | ![Screenshot 2023-07-04 at 10 05 50](https://github.com/Shopify/polaris/assets/10282220/b65b912f-ac76-406d-adf4-0d13208d068f) | 
| **Without $se23** | ![Screenshot 2023-07-04 at 10 06 31](https://github.com/Shopify/polaris/assets/10282220/09a1f68e-36e6-4048-b5e8-33bff973012b) | ![Screenshot 2023-07-04 at 10 05 43](https://github.com/Shopify/polaris/assets/10282220/d7e7330b-a81e-4d1c-8ed1-135a41b0a390)  |

### WHAT is this pull request doing?

We now wrap the se23 specific padding in a `&:not(.Section-flush) {` to ensure we don't add the padding to flush components.

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2023-07-04 09:20 UTC, egenerat approved these changes

2023-07-04 09:29 UTC, jiricrispeyn approved these changes

2023-07-04 09:29 UTC, karrocon approved these changes

2023-07-05 13:04 UTC, samrose3 commented on polaris-react/src/components/LegacyCard/LegacyCard.scss
> +    }
Looks like there _could_ be some conflict with the [LegacyCard Experimental updates here](https://github.com/Shopify/polaris/pull/9558/files#diff-7f3b0e011920dd647877d678aab9a8d3f550013c626dd1b6d8be21dc8d23ca51R124-R127) or around these styles.

cc @qt314 could you check this doesn't affect your current PR?

2023-07-05 14:54 UTC, sophschneider commented on polaris-react/src/components/LegacyCard/LegacyCard.scss
> +    }
I think we should close this PR, the PR you linked fixes this and is merged!

2023-07-05 14:55 UTC, qt314 requested changes
This has already been fixed in https://github.com/Shopify/polaris/pull/9558!

2023-07-05 15:29 UTC, closed without merging