[Choice][Checkbox][RadioButton] Use CSS-native :hover styling
Shopify/polaris-react-archive pull request #9612
Opened 2023-07-05 06:27 UTC by jesstelford

_See https://github.com/Shopify/polaris/pull/9593 for context and why this is useful beyond just fixing a bug._

By using CSS-native hover styling, and pulling it up to the wrapping <label> it avoids an issue where the browser would briefly detect hover with the :hover pseudo selector setting `cursor: pointer`, but then get overwritten with the JS onMouseOver styles 100ms later to `cursor: default`, resulting in a flash of a pointy-hand for the cursor on disabled Checkbox.

https://github.com/Shopify/polaris/assets/612020/92a593b8-c670-46e9-ac28-790418574c07

> _Had to use my phone's "Slow Motion" camera to capture a video of it; none of the desktop recording software could get it_ 😓

2023-07-05 06:32 UTC, jesstelford commented on polaris-react/src/components/Checkbox/tests/Checkbox.test.tsx
> -      label!.trigger('onMouseOver');
This doesn't exist anymore.

... Also, why are our tests asserting against internal implementation details?

2023-07-06 05:20 UTC, gwyneplaine requested changes

2023-07-06 05:20 UTC, gwyneplaine commented on polaris-react/src/components/RadioButton/RadioButton.scss
> +    .ChoiceLabel:hover & {
We shouldn't need to add the .ChoiceLabel:hover specificity for focus-ring styles, can likely remove this.

2023-07-06 05:20 UTC, gwyneplaine commented on polaris-react/src/components/Choice/Choice.tsx
> -  onMouseOut,
Weary of removing onMouseOut and onMouseOver as props on `Choice` 
Considering there are [usages of this component ](https://grokt.shopify.io/results?q=%3CChoice+lang%3Atsx+-r%3APolaris) outside of Polaris.

2023-07-06 06:40 UTC, jesstelford commented on polaris-react/src/components/Choice/Choice.tsx
> -  onMouseOut,
Thankfully that's not Polaris's `Choice`; it's [not even exported from `@shopify/polaris`](https://github.com/Shopify/polaris/blob/main/polaris-react/src/index.ts), and the only usage within Polaris is RadioButton/Checkbox. 🎉

2023-07-06 06:47 UTC, gwyneplaine approved these changes

2023-07-06 08:19 UTC, merged