[SkeletonBodyText] Add wrapper to SkeletonBodyText
Shopify/polaris-react-archive pull request #9764
Opened 2023-07-19 18:44 UTC by andy-schneidr

Wrap individual lines of SkeletonBodyText in a div with width 100% This allows the lines to fill available space in cases when width isn't specified, as an item in a HorizontalStack for example.

### WHY are these changes introduced?

Fixes #9703 

### WHAT is this pull request doing?

Adds a `<div width=100%>` wrapper around `<SkeletonBodyText>` lines, so that they'll fill available horizontal space.

Before:
![image](https://github.com/Shopify/polaris/assets/107708248/b82da79b-0015-477d-b012-fe25ddc2828b)

After:
![image](https://github.com/Shopify/polaris/assets/107708248/2dcfd6b5-7d7c-4486-94cf-9f626c1b4fac)

As a note, in the example `<SkeletonThumbnail>` has a tendency to get squished in `<HorizontalStack>`s. Is this something we want to address? The most straightforward workaround I've found is to just wrap it in a `<div>`, no other styling required.

### How to 🎩

With the changes pulled down, run `yarn dev` and take a look at the examples under `SkeletonBodyText` and `SkeletonPage` - There shouldn't be any changes, with the exception of `SkeletonBodyText - Default` - The last line shows with a width of 80% now. I think this is closer to the intended behaviour, looking at the difference between the example in the [doc](https://polaris.shopify.com/components/feedback-indicators/skeleton-body-text) and how it looks in the code sandbox 😮 

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';

import {
  Card,
  Text,
  HorizontalStack,
  Layout,
  LegacyStack,
  Page,
  SkeletonBodyText,
  SkeletonThumbnail,
} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      <Card>
        <Text variant="headingMd" as="h2">
          3 Lines, LegacyStack with LegacyStack.Item fill :D
        </Text>
        <Layout.Section />
        <LegacyStack wrap={false}>
          <SkeletonThumbnail size="small" />
          <LegacyStack.Item fill>
            <SkeletonBodyText lines={3} />
          </LegacyStack.Item>
        </LegacyStack>
      </Card>
      <Layout.Section />
      <Card>
        <Text variant="headingMd" as="h2">
          3 lines, in a HorizontalStack
        </Text>
        <Layout.Section />
        <HorizontalStack wrap={false} blockAlign="start" gap="4">
          <SkeletonThumbnail size="small" />
          <SkeletonBodyText lines={3} />
        </HorizontalStack>
      </Card>
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2023-07-19 18:50 UTC, andy-schneidr commented
@jesstelford Feel free to add/remove reviewers to this at your leisure, I'm a bit unfamiliar as to who else would be a good candidate! Also, let me know if you'd like to see a changelog entry for this.

2023-07-24 05:24 UTC, jesstelford requested changes
This looks good to me, but it needs a changset (patch) for the `@shopify/polaris` package.

2023-07-24 15:22 UTC, andy-schneidr commented
> This looks good to me, but it needs a changeset (patch) for the `@shopify/polaris` package

Thanks @jesstelford! I've added a changeset 😄 Let me know if it needs any changes.

2023-07-25 02:11 UTC, jesstelford approved these changes

2023-07-25 02:12 UTC, merged