Bulk actions style updates
Shopify/polaris-react-archive pull request #9819
Opened 2023-07-24 22:08 UTC by aveline

### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-summer-editions/issues/973

### WHAT is this pull request doing?

Updates padding, border radius, and add custom button style overrides to Bulk Actions. Adding the custom button style overrides is not a scalable pattern and this should be revisited.

Before
<img width="467" alt="Screenshot 2023-07-24 at 3 05 09 PM" src="https://github.com/Shopify/polaris/assets/3474483/29cb559e-38f6-4180-9775-458b32654f8f">

After
<img width="502" alt="Screenshot 2023-07-24 at 3 04 55 PM" src="https://github.com/Shopify/polaris/assets/3474483/4cc4b07d-5fbe-4649-8e45-bbfe61fe8cb0">

### How to 🎩
Review in Storybook with the beta flag turned on

2023-07-25 03:50 UTC, sarahill requested changes
There are some left over inner shadows showing up by default and on hover that need to be removed

expected
<img width="477" alt="image" src="https://github.com/Shopify/polaris/assets/8629173/b1f58d69-9895-40be-9b7d-6df206f45281">

actual
<img width="220" alt="image" src="https://github.com/Shopify/polaris/assets/8629173/009c51f7-27b6-4969-b3fa-56d5127544ba">
<img width="225" alt="image" src="https://github.com/Shopify/polaris/assets/8629173/3b0b417a-3105-4fef-86b9-d164c7dac54a">

2023-07-25 17:23 UTC, aveline commented
@sarahill 🤦‍♀️ should be fixed now, updated the screenshots above and included hover and active states!

2023-07-25 19:07 UTC, sarahill approved these changes

2023-08-14 17:36 UTC, lgriffee approved these changes
✨

2023-08-14 18:58 UTC, merged