Add critical section to the card component
Shopify/polaris-react-archive pull request #9881
Opened 2023-08-03 15:46 UTC by fatimasajadi

### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris/issues/9882

### WHAT is this pull request doing?

We needed to introduce a new card to the ProductDetails page, tailored specifically for suspended products. This card will display relevant information when a product is in the suspended state and provide the user with options to delete the product or directly submit a counter-notice. In order to do that we need to have the option to have background and border with critical color in the Polaris Card component. This PR adds the necessary styles in order to achieve that ability.

[Storybook Link](http://192.168.2.18:6006/?path=/story/all-components-card--with-critical-section)
<img width="2514" alt="Screenshot 2023-08-03 at 2 21 00 PM" src="https://github.com/Shopify/polaris/assets/6689267/f024e4b8-d296-42bd-a60d-9fc2ba80c7cc">

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2023-08-03 19:10 UTC, kyledurand requested changes
I'd like to focus on what's blocking this card from being built in web vs in Polaris. The only thing I see is that we don't export the ShadowBevel component which is used to build the uplifted card.

The other challenge there is getting the critical border to show up with the ShadowBevel wrapper on Box.

cc @aaronccasanova. I do understand the need for this component but I think we should explore other options before baking it into Polaris

2023-08-03 19:10 UTC, kyledurand commented on polaris-react/src/components/Card/Card.stories.tsx
> +  const {polarisSummerEditions2023} = useFeatures();
Did you mean to use this somewhere?

2023-08-03 19:10 UTC, kyledurand commented on polaris-react/src/components/Card/Card.tsx
> +  hasCriticalStatus?: boolean;
We're moving away from boolean props like this. It should be `tone` with `critical` option

2023-08-03 19:10 UTC, kyledurand commented on polaris-react/src/components/Card/Card.tsx
> +          borderWidth="1"
This is the non-uplifted box so you wouldn't see this in the admin

2023-08-03 20:56 UTC, kyledurand commented
[This is what I mean by composability](https://codesandbox.io/s/priceless-torvalds-rx3nty?file=/App.tsx) I don't think this needs to be a part of Polaris but let me know if you run into anything Polaris is missing, any blockers, and I'll give you a hand

2023-08-03 21:19 UTC, fatimasajadi commented
> [This is what I mean by composability](https://codesandbox.io/s/priceless-torvalds-rx3nty?file=/App.tsx) I don't think this needs to be a part of Polaris but let me know if you run into anything Polaris is missing, any blockers, and I'll give you a hand

I agree with you. We should not need to change anything in Polaris, in order to achieve what we wanted. Thanks so much for taking the time and explain this. I will share this with my team and see if there is anything I'm missing.

2023-08-04 16:38 UTC, fatimasajadi commented
We all agreed that we do not need to make changes to root Polaris in order to build the custom card for suspended products.

2023-08-04 16:38 UTC, closed without merging